/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtcc;

import BancoDeDados.FornecedorBean;
import BancoDeDados.FornecedorDao;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jéssica
 */
public class CadFornecedor extends javax.swing.JFrame {

    private DefaultTableModel DefaultTableModel;
    FornecedorDao fd = new FornecedorDao();
    FornecedorBean fb;

    public void pegaInformacoesDosCampos() {
        fb = new FornecedorBean();

        fb.setTxtFantasia(txtFantasia.getText());
        fb.setTxtCNPJ(txtCNPJ.getText());
        fb.setTipo(Tipo.getSelectedIndex());
        fb.setTxtNome(txtNome.getText());
        fb.setTxtTelefone(txtTelefone.getText());
        fb.setTxtComercial(txtComercial.getText());
        fb.setTxtCelular(txtCelular.getText());
        fb.setTxtFAX(txtFAX.getText());
        fb.setTxtHP(txtHP.getText());
        fb.setTxtEmail(txtEmail.getText());
        fb.setTxtObs(txtObs.getText());
        if (caminhoDaImagem == null) {
            imagemPadrao();
        } else {
            fb.setImagem(caminhoDaImagem);
        }

        fb.setTxtCEP(txtCEP.getText());
        fb.setTxtEndereco(txtEndereco.getText());
        fb.setTxtNRO(txtNRO.getText());
        fb.setTxtComplemento(txtComplemento.getText());
        fb.setTxtBairro(txtBairro.getText());
        fb.setTxtCidade(txtCidade.getText());
        fb.setTipoEnd(Tipo_End.getSelectedIndex());
        fb.setUf(txtUF.getSelectedIndex());

    }

    private void imagemPadrao() {

        String file = "./imagemPadrão/padrão.png";
        lblImagem.setIcon(new ImageIcon(file));
        ImageIcon icon = new ImageIcon(file);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(121, 123, java.awt.Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newImg);
        lblImagem.setIcon(newIcon);
        lblImagem.setSize(104, 14);
        BancoDeDados.FornecedorBean Forn = new BancoDeDados.FornecedorBean();
        Forn.setImagem("./imagemPadrão/padrão.png");
    }

    public CadFornecedor() {
        initComponents();

        txtCodigo.setDocument(new Limite_Digitos(10));
        txtFantasia.setDocument(new Limite_Digitos(40));
        txtNome.setDocument(new Limite_Digitos(40));
        txtTelefone.setDocument(new Limite_Digitos(18));
        txtComercial.setDocument(new Limite_Digitos(18));
        txtCelular.setDocument(new Limite_Digitos(18));
        txtFAX.setDocument(new Limite_Digitos(18));
        txtHP.setDocument(new Limite_Digitos(20));
        txtEmail.setDocument(new Limite_Digitos(40));
        txtObs.setDocument(new Limite_Digitos(1000));
        int[] anIntArray = new int[10];
        txtObs.setLineWrap(true);
        setIcon();

    }

    public void limparCampos() {

        String message = " Deseja realmente limpar tudo? ";
        String title = "Limpar Dados";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            apagarCampos();

        }
    }

    public void apagarCampos() {
        txtCodigo.setText("");
        txtFantasia.setText("");
        txtCNPJ.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        txtComercial.setText("");
        txtCelular.setText("");
        txtFAX.setText("");
        txtHP.setText("");
        txtEmail.setText("");
        txtObs.setText("");
        Tipo.setSelectedIndex(0);
        lblImagem.setIcon(null);
    }

    public void apagarEndereco() {
        txtCEP.setText("");
        txtEndereco.setText("");
        txtNRO.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        Tipo_End.setSelectedIndex(0);
        txtUF.setSelectedIndex(0);

    }

    public void preparaForm() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        CadastroFornecedor = new javax.swing.JDesktopPane();
        GerarEndereco = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblIcon2 = new javax.swing.JLabel();
        txtNRO = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnFechar2 = new javax.swing.JButton();
        btnLimpar2 = new javax.swing.JButton();
        lblTipo_End = new javax.swing.JLabel();
        lblNRO = new javax.swing.JLabel();
        Tipo_End = new javax.swing.JComboBox();
        lblEndereco = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtCEP = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("#####-###");  
            txtCEP = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        lblCEP = new javax.swing.JLabel();
        txtUF = new javax.swing.JComboBox();
        txtEndereco = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##) ####-####");
            txtTelefone= new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        btnSalvar1 = new javax.swing.JButton();
        btnFechar1 = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtFantasia = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##) #####-####");  
            txtCelular= new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        btnTirar = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblFantasia = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        Tipo = new javax.swing.JComboBox();
        lblCNPJ = new javax.swing.JLabel();
        lblCom = new javax.swing.JLabel();
        txtComercial = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##) ####-####");  
            txtComercial= new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        lblEmail = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JFormattedTextField();
        lblCNPJ2 = new javax.swing.JLabel();
        lblFAX = new javax.swing.JLabel();
        txtFAX = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##) ####-####");
            txtFAX= new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        txtEmail = new javax.swing.JTextField();
        lblHP = new javax.swing.JLabel();
        lblObs = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        btnInternet = new javax.swing.JButton();
        btnLimpar1 = new javax.swing.JButton();
        gerar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        lblCor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedores");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CadastroFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        CadastroFornecedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GerarEndereco.setTitle("Cadastro de Endereço");
        GerarEndereco.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/dtcc/iconframe.png"))); // NOI18N
        GerarEndereco.setVisible(false);
        GerarEndereco.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBairro.setText("Bairro:");
        jPanel1.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lblCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCidade.setText("Cidade:");
        jPanel1.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 190, -1, -1));

        lblTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo2.setText("Controle de Endereço");
        jPanel1.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 11, -1, 32));
        jPanel1.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 188, 154, -1));

        lblUF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUF.setText("UF:");
        jPanel1.add(lblUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 158, -1, -1));
        jPanel1.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 156, 416, -1));

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Endereço.png"))); // NOI18N
        jPanel1.add(lblIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 36, -1));
        jPanel1.add(txtNRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 127, 60, -1));
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 188, 142, -1));

        btnInserir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 100, 30));

        btnFechar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFechar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair_1.png"))); // NOI18N
        btnFechar2.setText("Fechar");
        btnFechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnFechar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, 30));

        btnLimpar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        btnLimpar2.setText("Limpar");
        btnLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 100, 30));

        lblTipo_End.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipo_End.setText("Tipo de Endereço:");
        jPanel1.add(lblTipo_End, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 123, -1));

        lblNRO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNRO.setText("NRO:");
        jPanel1.add(lblNRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 129, -1, -1));

        Tipo_End.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0- Residencial", "1- Comercial"}));
        Tipo_End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipo_EndActionPerformed(evt);
            }
        });
        jPanel1.add(Tipo_End, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 97, 133, -1));

        lblEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEndereco.setText("Endereço:");
        jPanel1.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 66, -1));

        lblComplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblComplemento.setText("Complemento:");
        jPanel1.add(lblComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 96, -1, -1));

        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });
        jPanel1.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 97, 129, -1));

        lblCEP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCEP.setText("CEP:");
        jPanel1.add(lblCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 99, -1, -1));

        txtUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel1.add(txtUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 156, 60, -1));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 127, 439, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 621, -1));

        GerarEndereco.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 654, 311));

        CadastroFornecedor.add(GerarEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        CadastroFornecedor.setLayer(GerarEndereco, javax.swing.JLayeredPane.POPUP_LAYER);

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNome.setText("Nome:");
        CadastroFornecedor.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 118, -1, -1));

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipo.setText("Tipo:");
        CadastroFornecedor.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 50, 20));

        lblCel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCel.setText("Cel:");
        CadastroFornecedor.add(lblCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 146, -1, 30));

        lblTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefone.setText("Telefone:");
        CadastroFornecedor.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));
        CadastroFornecedor.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        btnSalvar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar peq.png"))); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(btnSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 100, -1));

        btnFechar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair_1.png"))); // NOI18N
        btnFechar1.setText("Fechar");
        btnFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar1ActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(btnFechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 100, -1));

        btnRemover.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 228, 121, -1));

        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 116, 550, -1));
        CadastroFornecedor.add(txtFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 310, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 255));
        txtCodigo.setEnabled(false);
        CadastroFornecedor.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 150, -1));
        CadastroFornecedor.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 140, -1));

        btnTirar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Webcam.png"))); // NOI18N
        btnTirar.setText("Tirar Foto");
        btnTirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTirarActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(btnTirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 136, 121, -1));

        btnSelecionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pasta de foto.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 166, 121, -1));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCodigo.setText("Código:");
        CadastroFornecedor.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblFantasia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFantasia.setText("Fantasia:");
        CadastroFornecedor.add(lblFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 20));
        CadastroFornecedor.add(txtHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 340, -1));

        Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0- Cliente Ativo", "1- Cliente Bloqueado", "2- Cliente Inativo"}));
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 150, 30));

        lblCNPJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCNPJ.setText("CNPJ:");
        CadastroFornecedor.add(lblCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblCom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCom.setText("Com:");
        CadastroFornecedor.add(lblCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 146, -1, 20));
        CadastroFornecedor.add(txtComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 155, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setText("E-mail:");
        CadastroFornecedor.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 208, -1, -1));

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJ.setText("");
        txtCNPJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCNPJMouseClicked(evt);
            }
        });
        txtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJActionPerformed(evt);
            }
        });
        txtCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCNPJKeyReleased(evt);
            }
        });
        CadastroFornecedor.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, -1));

        lblCNPJ2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCNPJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dtcc/invalido.png"))); // NOI18N
        CadastroFornecedor.add(lblCNPJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 30, 30));

        lblFAX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFAX.setText("FAX:");
        CadastroFornecedor.add(lblFAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 177, -1, -1));
        CadastroFornecedor.add(txtFAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 160, -1));
        CadastroFornecedor.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 206, 550, -1));

        lblHP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHP.setText("HP:");
        CadastroFornecedor.add(lblHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        lblObs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblObs.setText("Obs:");
        CadastroFornecedor.add(lblObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 244, 64, -1));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/padrão.png"))); // NOI18N
        lblImagem.setText("     ");
        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagem.setMaximumSize(new java.awt.Dimension(0, 0));
        lblImagem.setMinimumSize(new java.awt.Dimension(0, 0));
        CadastroFornecedor.add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 121, 123));

        btnInternet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Internet.png"))); // NOI18N
        btnInternet.setText("Internet");
        btnInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInternetActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(btnInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 196, 121, -1));

        btnLimpar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        btnLimpar1.setText("Limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(btnLimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 100, -1));

        gerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gerar Rota.png"))); // NOI18N
        gerar.setText("Inserir Endereço");
        gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarActionPerformed(evt);
            }
        });
        CadastroFornecedor.add(gerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 314, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Cadastro de Fornecedores");
        CadastroFornecedor.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fornecedores Grande.png"))); // NOI18N
        CadastroFornecedor.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane3.setViewportView(txtObs);

        CadastroFornecedor.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 550, 60));

        lblCor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lblcor.png"))); // NOI18N
        CadastroFornecedor.add(lblCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 390));

        getContentPane().add(CadastroFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 390));

        setSize(new java.awt.Dimension(931, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarActionPerformed
        CadastroFornecedor.setVisible(true);
        GerarEndereco.setVisible(true);
    }//GEN-LAST:event_gerarActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void btnInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternetActionPerformed
        Desktop desk = java.awt.Desktop.getDesktop();
        try {
            desk.browse(new java.net.URI("https://www.google.com.br/imghp?hl=pt-BR&tab=wi&ei=hFvtUqmWLIjskQePxoDADQ&ved=0CAQQqi4oAg//"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnInternetActionPerformed

    private void txtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJActionPerformed

    private void txtCNPJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCNPJMouseClicked

    }//GEN-LAST:event_txtCNPJMouseClicked

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        BancoDeDados.FornecedorBean F = new BancoDeDados.FornecedorBean();
        F.setImagem(this.retornacaminho());
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnTirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTirarActionPerformed
        Form_webcam LG = new Form_webcam();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTirarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMouseClicked

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        lblImagem.setIcon(null);
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar1ActionPerformed
        CadCliente LG = new CadCliente();
        LG.setVisible(false);
        dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_btnFechar1ActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed

        if ((txtFantasia.getText().isEmpty()) || (txtCNPJ.getText().isEmpty()) || (txtComercial.getText().equals("(  )     -    "))) {
            JOptionPane.showMessageDialog(null, "Alguns campos não podem retornar vazios");
        } else {
            pegaInformacoesDosCampos();
            fd.inserirFornecedor(fb);
            JOptionPane.showMessageDialog(null, "Fornecedor(a) " + txtNome.getText() + " cadastrado com sucesso! ", "Aviso", 1);
            apagarCampos();
            apagarEndereco();
        }
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        /*        pegaInformacoesDosCampos();
         fd.inserirFornecedor(fb);
         JOptionPane.showMessageDialog(null, "Endereço do fornecedor " + txtNome.getText() + " cadastrado com sucesso! ", "Aviso", 1);
         apagarEndereco();*/
        GerarEndereco.setVisible(false);
        CadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnFechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar2ActionPerformed
        GerarEndereco.setVisible(false);
        CadastroFornecedor.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_btnFechar2ActionPerformed

    private void btnLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar2ActionPerformed
        apagarEndereco();
    }//GEN-LAST:event_btnLimpar2ActionPerformed

    private void Tipo_EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipo_EndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tipo_EndActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        buscaCep();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtCNPJKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNPJKeyReleased
        validandoCNPJ();
    }//GEN-LAST:event_txtCNPJKeyReleased

    public void run() {
        new CadFornecedor().setVisible(true);

    }
    ;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane CadastroFornecedor;
    private javax.swing.JInternalFrame GerarEndereco;
    private javax.swing.JComboBox Tipo;
    private javax.swing.JComboBox Tipo_End;
    private javax.swing.JButton btnFechar1;
    private javax.swing.JButton btnFechar2;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnInternet;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnTirar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton gerar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCNPJ2;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFAX;
    private javax.swing.JLabel lblFantasia;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNRO;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipo_End;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUF;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComercial;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFAX;
    private javax.swing.JTextField txtFantasia;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtNRO;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JComboBox txtUF;
    // End of variables declaration//GEN-END:variables

    private void validandoCNPJ() {
        Icon icon = new ImageIcon(getClass().getResource("valido.png"));
        Icon icon2 = new ImageIcon(getClass().getResource("invalido.png"));
        // aqui vc coloca a rotina de validacao  
        Boolean validado;
        validaCnpj vCnpj = new validaCnpj();
        validado = vCnpj.isCnpjValido(txtCNPJ.getText());
        //validacnpj 
        if (validado) {
            lblCNPJ2.setIcon(icon);
        } else {
            lblCNPJ2.setIcon(icon2);
        }

    }

    public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(txtCEP.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            txtEndereco.setText(webServiceCep.getLogradouroFull());
            txtCidade.setText(webServiceCep.getCidade());
            txtBairro.setText(webServiceCep.getBairro());
            txtUF.setSelectedItem(webServiceCep.getUf());
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "CEP Inválido ! " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconframe.png"))); //To change body of generated methods, choose Tools | Templates.
    }

    String caminhoDaImagem;

    private String retornacaminho() throws java.lang.NullPointerException {

        String file = "";
        JFileChooser dlg = new JFileChooser();
        int opcion = dlg.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            file += dlg.getSelectedFile().getPath();
            lblImagem.setIcon(new ImageIcon(file));
            ImageIcon icon = new ImageIcon(file);
            Image img = icon.getImage();
            Image newImg = img.getScaledInstance(121, 123, java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImg);        // TODO add your handling code here:
            lblImagem.setIcon(newIcon);
            lblImagem.setSize(104, 14);
            caminhoDaImagem = file;

            //   System.out.println("Caminho do arquivo : "+file);
        }
        return file;

    }
}
