/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtcc;

import BancoDeDados.FuncionarioBean;
import BancoDeDados.FuncionarioDao;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jéssica
 */
public class CadFuncionario extends javax.swing.JFrame {

    private DefaultTableModel DefaultTableModel;
    FuncionarioDao fund = new FuncionarioDao();
    FuncionarioBean funb;

    public void pegaInformacoesDosCampos() {
        funb = new FuncionarioBean();
        funb.setTxtNome(txtNome.getText());
        funb.setSexo(Sexo.getSelectedIndex());
        funb.setTxtCPF(txtCPF.getText());
        funb.setTxtData(txtData.getText());
        funb.setTxtRG(txtCPF.getText());
        if (caminhoDaImagem == null) {
            imagemPadrao();
        } else {
            funb.setImagem(caminhoDaImagem);
        }

        funb.setTxtObs(txtObs.getText());
        funb.setTxtTelefone(txtTelefone.getText());
        funb.setTxtCelular(txtCelular.getText());
        funb.setTxtEmail(txtEmail.getText());
        funb.setTxtFAX(txtFAX.getText());
        funb.setTxtComercial(txtComercial.getText());
        funb.setTxtCEP(txtCEP.getText());
        funb.setTxtEndereco(txtEndereco.getText());
        funb.setTxtNRO(txtNRO.getText());
        funb.setTxtComplemento(txtComplemento.getText());
        funb.setTxtBairro(txtBairro.getText());
        funb.setTxtCidade(txtCidade.getText());
        funb.setTipoEnd(Tipo_End.getSelectedIndex());
        funb.setUf(txtUF.getSelectedIndex());
    }

    private void imagemPadrao() {

        String file = "./imagemPadrão/padrão.png";
        lblImagem.setIcon(new ImageIcon(file));
        ImageIcon icon = new ImageIcon(file);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(121, 123, java.awt.Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newImg);
        lblImagem.setIcon(newIcon);
        lblImagem.setSize(104, 14);
        BancoDeDados.FuncionarioBean F = new BancoDeDados.FuncionarioBean();
        F.setImagem("./imagemPadrão/padrão.png");
    }

    public CadFuncionario() {
        initComponents();

        Codigo.setDocument(new Limite_Digitos(10));
        txtNome.setDocument(new Limite_Digitos(40));
        txtTelefone.setDocument(new Limite_Digitos(18));
        txtCelular.setDocument(new Limite_Digitos(18));
        txtEmail.setDocument(new Limite_Digitos(40));
        txtObs.setDocument(new Limite_Digitos(1000));
        txtObs.setLineWrap(true);
        int[] anIntArray = new int[10];
        setIcon();

    }

    public void limparCampos() {

        String message = " Deseja realmente limpar tudo? ";
        String title = "Limpar Dados";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            apagarCampos();
        }
    }

    public void apagarCampos() {
        Codigo.setText("");
        txtCPF.setText("");
        txtNome.setText("");
        lblRG.setText("");
        txtData.setText("");
        txtTelefone.setText("");
        txtCelular.setText("");
        txtComercial.setText("");
        txtFAX.setText("");
        txtEmail.setText("");
        txtObs.setText("");
        Sexo.setSelectedIndex(0);
        lblImagem.setIcon(null);

    }

    public void apagarEndereco() {
        txtCEP.setText("");
        txtEndereco.setText("");
        txtNRO.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        Tipo_End.setSelectedIndex(0);
        txtUF.setSelectedIndex(0);

    }

    public void preparaForm() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        CadastroFuncionario = new javax.swing.JDesktopPane();
        GerarEndereco = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblIcon2 = new javax.swing.JLabel();
        txtNRO = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        btnSalvar2 = new javax.swing.JButton();
        btnFechar2 = new javax.swing.JButton();
        btnLimpar2 = new javax.swing.JButton();
        lblTipo_End = new javax.swing.JLabel();
        lblNRO = new javax.swing.JLabel();
        Tipo_End = new javax.swing.JComboBox();
        lblEndereco = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtCEP = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("#####-###");  
            txtCEP = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        lblCEP = new javax.swing.JLabel();
        txtUF = new javax.swing.JComboBox();
        txtEndereco = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##) ####-####");  
            txtTelefone= new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        Codigo = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##) #####-####");  
            txtCelular = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        lblCPF2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        gerar = new javax.swing.JButton();
        Sexo = new javax.swing.JComboBox();
        lblCom = new javax.swing.JLabel();
        txtComercial = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##) ####-####");  
            txtComercial= new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        lblFAX = new javax.swing.JLabel();
        txtFAX = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("(##) ####-####");
            txtFAX= new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        lblCor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionarios");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CadastroFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        CadastroFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GerarEndereco.setTitle("Cadastro de Endereço");
        GerarEndereco.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/dtcc/iconframe.png"))); // NOI18N
        GerarEndereco.setVisible(false);
        GerarEndereco.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBairro.setText("Bairro:");
        jPanel1.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lblCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCidade.setText("Cidade:");
        jPanel1.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 190, -1, -1));

        lblTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo2.setText("Controle de Endereço");
        jPanel1.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 11, -1, 32));
        jPanel1.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 188, 154, -1));

        lblUF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUF.setText("UF:");
        jPanel1.add(lblUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 158, -1, -1));
        jPanel1.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 156, 416, -1));

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Endereço.png"))); // NOI18N
        jPanel1.add(lblIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 36, -1));
        jPanel1.add(txtNRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 127, 60, -1));
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 188, 142, -1));

        btnSalvar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Inserir.png"))); // NOI18N
        btnSalvar2.setText("Inserir");
        btnSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 100, 30));

        btnFechar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFechar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair_1.png"))); // NOI18N
        btnFechar2.setText("Fechar");
        btnFechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnFechar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, 30));

        btnLimpar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        btnLimpar2.setText("Limpar");
        btnLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 100, 30));

        lblTipo_End.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipo_End.setText("Tipo de Endereço:");
        jPanel1.add(lblTipo_End, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 123, -1));

        lblNRO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNRO.setText("NRO:");
        jPanel1.add(lblNRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 129, -1, -1));

        Tipo_End.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0- Residencial", "1- Comercial"}));
        Tipo_End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipo_EndActionPerformed(evt);
            }
        });
        jPanel1.add(Tipo_End, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 97, 133, -1));

        lblEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEndereco.setText("Endereço:");
        jPanel1.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 66, -1));

        lblComplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblComplemento.setText("Complemento:");
        jPanel1.add(lblComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 96, -1, -1));

        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });
        jPanel1.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 97, 129, -1));

        lblCEP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCEP.setText("CEP:");
        jPanel1.add(lblCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 99, -1, -1));

        txtUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel1.add(txtUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 156, 60, -1));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 127, 439, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 621, -1));

        GerarEndereco.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 654, 311));

        CadastroFuncionario.add(GerarEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        CadastroFuncionario.setLayer(GerarEndereco, javax.swing.JLayeredPane.POPUP_LAYER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");
        CadastroFuncionario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblRG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRG.setText("RG:");
        CadastroFuncionario.add(lblRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, 20));
        CadastroFuncionario.add(txtRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 190, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CPF:");
        CadastroFuncionario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Sexo:");
        CadastroFuncionario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cel:");
        CadastroFuncionario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Telefone:");
        CadastroFuncionario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar peq.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        CadastroFuncionario.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 100, -1));

        btnFechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair_1.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        CadastroFuncionario.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, -1, -1));

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        CadastroFuncionario.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 100, -1));
        CadastroFuncionario.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 393, -1));

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CadastroFuncionario.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 110, 30));
        CadastroFuncionario.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 159, -1));

        Codigo.setEditable(false);
        Codigo.setBackground(new java.awt.Color(204, 204, 255));
        Codigo.setEnabled(false);
        CadastroFuncionario.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 56, 151, -1));
        CadastroFuncionario.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 193, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pasta de foto.png"))); // NOI18N
        jButton2.setText("Selecionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        CadastroFuncionario.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 121, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Cadastro de Funcionarios");
        CadastroFuncionario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 45));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Código:");
        CadastroFuncionario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFKeyReleased(evt);
            }
        });
        CadastroFuncionario.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, -1));

        lblCPF2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCPF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dtcc/invalido.png"))); // NOI18N
        CadastroFuncionario.add(lblCPF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 30, 20));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setText("E-mail:");
        CadastroFuncionario.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        CadastroFuncionario.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 398, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Data de Nasc:");
        CadastroFuncionario.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Obs:");
        CadastroFuncionario.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 40, -1));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/padrão.png"))); // NOI18N
        lblImagem.setText("     ");
        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagem.setMaximumSize(new java.awt.Dimension(0, 0));
        lblImagem.setMinimumSize(new java.awt.Dimension(0, 0));
        CadastroFuncionario.add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 121, 123));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Funcionarios Grande.png"))); // NOI18N
        CadastroFuncionario.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Webcam.png"))); // NOI18N
        jButton11.setText("Tirar Foto");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        CadastroFuncionario.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 121, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Internet.png"))); // NOI18N
        jButton12.setText("Internet");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        CadastroFuncionario.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 121, -1));

        btnRemover.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        CadastroFuncionario.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 121, -1));

        gerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gerar Rota.png"))); // NOI18N
        gerar.setText("Inserir Endereço");
        gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarActionPerformed(evt);
            }
        });
        CadastroFuncionario.add(gerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0- Feminino", "1- Masculino"}));
        Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexoActionPerformed(evt);
            }
        });
        CadastroFuncionario.add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 151, -1));

        lblCom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCom.setText("Com:");
        CadastroFuncionario.add(lblCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 147, -1, -1));
        CadastroFuncionario.add(txtComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 145, 157, -1));

        lblFAX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFAX.setText("FAX:");
        CadastroFuncionario.add(lblFAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));
        CadastroFuncionario.add(txtFAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 159, -1));

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane3.setViewportView(txtObs);

        CadastroFuncionario.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 610, 90));

        lblCor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lblcor.png"))); // NOI18N
        CadastroFuncionario.add(lblCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 380));

        getContentPane().add(CadastroFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 380));

        setSize(new java.awt.Dimension(932, 419));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        CadFuncionario LG = new CadFuncionario();
        LG.setVisible(false);
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BancoDeDados.FuncionarioBean F = new BancoDeDados.FuncionarioBean();
        F.setImagem(this.retornacaminho());

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Form_webcam LG = new Form_webcam();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Desktop desk = java.awt.Desktop.getDesktop();
        try {
            desk.browse(new java.net.URI("https://www.google.com.br/imghp?hl=pt-BR&tab=wi&ei=hFvtUqmWLIjskQePxoDADQ&ved=0CAQQqi4oAg//"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        lblImagem.setIcon(null);
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarActionPerformed
        CadastroFuncionario.setVisible(true);
        GerarEndereco.setVisible(true);
    }//GEN-LAST:event_gerarActionPerformed

    private void SexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if ((txtNome.getText().isEmpty()) || (lblRG.getText().isEmpty()) || (txtCPF.getText().isEmpty()) || (txtTelefone.getText().equals("(  )    -    ")) || (txtData.getText().equals("  /  /    "))) {
            JOptionPane.showMessageDialog(null, "Alguns campos não podem retornar vazios");
        } else {
            pegaInformacoesDosCampos();
            fund.inserirFuncionario(funb);
            JOptionPane.showMessageDialog(null, "Funcionario(a) " + txtNome.getText() + " cadastrado com sucesso! ", "Aviso", 1);
            apagarCampos();
            apagarEndereco();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar2ActionPerformed
        /*        pegaInformacoesDosCampos();
         fund.inserirFuncionario(funb);
         JOptionPane.showMessageDialog(null, "Endereço do funcionario " + txtNome.getText() + " cadastrado com sucesso! ", "Aviso", 1);
         apagarEndereco();*/
        GerarEndereco.setVisible(false);
        CadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_btnSalvar2ActionPerformed

    private void btnFechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar2ActionPerformed
        GerarEndereco.setVisible(false);
        CadastroFuncionario.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_btnFechar2ActionPerformed

    private void btnLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar2ActionPerformed
        apagarEndereco();
    }//GEN-LAST:event_btnLimpar2ActionPerformed

    private void Tipo_EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipo_EndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tipo_EndActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        buscaCep();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyReleased
        validandoCpf();        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFKeyReleased

    public void run() {
        new CadFuncionario().setVisible(true);

    }
    ;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane CadastroFuncionario;
    private javax.swing.JTextField Codigo;
    private javax.swing.JInternalFrame GerarEndereco;
    private javax.swing.JComboBox Sexo;
    private javax.swing.JComboBox Tipo_End;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFechar2;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton gerar;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF2;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFAX;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNRO;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblTipo_End;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUF;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComercial;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFAX;
    private javax.swing.JTextField txtNRO;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JComboBox txtUF;
    // End of variables declaration//GEN-END:variables

    public void validandoCpf() {
        Icon icon = new ImageIcon(getClass().getResource("valido.png"));
        Icon icon2 = new ImageIcon(getClass().getResource("invalido.png"));
        // aqui vc coloca a rotina de validacao  
        Boolean validado;
        ValidaCpf cpf = new ValidaCpf();
        validado = cpf.validacpf(txtCPF.getText());
        //validacpf  
        if (validado) {
            lblCPF2.setIcon(icon);
        } else {
            lblCPF2.setIcon(icon2);
        }

    }

    public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(txtCEP.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            txtEndereco.setText(webServiceCep.getLogradouroFull());
            txtCidade.setText(webServiceCep.getCidade());
            txtBairro.setText(webServiceCep.getBairro());
            txtUF.setSelectedItem(webServiceCep.getUf());
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "CEP Inválido ! " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconframe.png")));
    }

    String caminhoDaImagem;

    private String retornacaminho() throws java.lang.NullPointerException {

        String file = "";
        JFileChooser dlg = new JFileChooser();
        int opcion = dlg.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            file += dlg.getSelectedFile().getPath();
            lblImagem.setIcon(new ImageIcon(file));
            ImageIcon icon = new ImageIcon(file);
            Image img = icon.getImage();
            Image newImg = img.getScaledInstance(121, 123, java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImg);        // TODO add your handling code here:
            lblImagem.setIcon(newIcon);
            lblImagem.setSize(104, 14);
            caminhoDaImagem = file;

            //   System.out.println("Caminho do arquivo : "+file);
        }
        return file;

    }
}
