/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtcc;

import BancoDeDados.conexao;
import java.awt.EventQueue;
import java.beans.Beans;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import BancoDeDados.OrcamentosBean;
import BancoDeDados.OrcamentosDao;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JoãoVitor
 */
public class Consulta_Instalacao extends JPanel {

    ResultSet rs;

    private DefaultTableModel DefaultTableModel;
    OrcamentosDao od = new OrcamentosDao();
    OrcamentosBean ob;

    public Consulta_Instalacao() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
            java.util.Collection data = query.getResultList();
            for (Object entity : data) {
                entityManager.refresh(entity);
            }
            list.clear();
            list.addAll(data);
            listarCadastros();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("bd?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT i FROM Instalacao i");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        ConsultaInstalacao = new javax.swing.JDesktopPane();
        GerarOrcamento = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtAno = new javax.swing.JFormattedTextField();
        txtFim = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Status = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JFormattedTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQtde = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JFormattedTextField();
        txtTotal = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCodInstalacao = new javax.swing.JTextField();
        PanelCor = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        codInstalacaoLabel = new javax.swing.JLabel();
        codCliLabel = new javax.swing.JLabel();
        nomeClienteLabel = new javax.swing.JLabel();
        codFunLabel = new javax.swing.JLabel();
        nomeFuncionarioLabel = new javax.swing.JLabel();
        primeiraManutencaoLabel = new javax.swing.JLabel();
        descricaoProdutoLabel = new javax.swing.JLabel();
        dataInstalacaoLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        codInstalacaoField = new javax.swing.JTextField();
        codCliField = new javax.swing.JTextField();
        nomeClienteField = new javax.swing.JTextField();
        codFunField = new javax.swing.JTextField();
        nomeFuncionarioField = new javax.swing.JTextField();
        primeiraManutencaoField = new javax.swing.JTextField();
        descricaoProdutoField = new javax.swing.JTextField();
        dataInstalacaoField = new javax.swing.JTextField();
        horarioField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        cmbPesquisar = new javax.swing.JComboBox();
        txtPesquisar = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        btnGerar = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(255, 255, 255));

        ConsultaInstalacao.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaInstalacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GerarOrcamento.setTitle("Orçamentos De Instalação");
        GerarOrcamento.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/dtcc/iconframe.png"))); // NOI18N
        GerarOrcamento.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salario grande.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Orçamentos De Instalação");

        btnFechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair peq.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(formListener);

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar peq.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(formListener);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Status:");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        jButton2.setText("Novo Orçamento");
        jButton2.addActionListener(formListener);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cliente:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Vendedor:");

        try {
            txtFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Orçamento n°");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ano:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Inicio:");

        Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0- Disponivel", "1- Indisponivel"}));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fim:");

        try {
            txtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtInicio.addActionListener(formListener);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 255));
        txtCodigo.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Qtde:");

        txtQtde.addKeyListener(formListener);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Preço Uni:");

        txtPreco.addKeyListener(formListener);

        txtTotal.addActionListener(formListener);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Total:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Descrição:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Desconto:");

        txtDesconto.addActionListener(formListener);
        txtDesconto.addKeyListener(formListener);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Cod Instalação:");

        txtCodInstalacao.setEditable(false);
        txtCodInstalacao.setBackground(new java.awt.Color(204, 204, 255));
        txtCodInstalacao.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtCodInstalacao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(146, 146, 146))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addGap(6, 6, 6)
                        .addComponent(btnFechar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodInstalacao)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar)
                        .addComponent(jButton2))
                    .addComponent(btnFechar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout GerarOrcamentoLayout = new javax.swing.GroupLayout(GerarOrcamento.getContentPane());
        GerarOrcamento.getContentPane().setLayout(GerarOrcamentoLayout);
        GerarOrcamentoLayout.setHorizontalGroup(
            GerarOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GerarOrcamentoLayout.setVerticalGroup(
            GerarOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ConsultaInstalacao.add(GerarOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 780, 280));

        PanelCor.setBackground(new java.awt.Color(255, 255, 255));
        PanelCor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codInstalacao}"));
        columnBinding.setColumnName("Cod Instalacao");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codCli}"));
        columnBinding.setColumnName("Cod Cli");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeCliente}"));
        columnBinding.setColumnName("Nome Cliente");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codFun}"));
        columnBinding.setColumnName("Cod Fun");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeFuncionario}"));
        columnBinding.setColumnName("Nome Funcionario");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${primeiraManutencao}"));
        columnBinding.setColumnName("Primeira Manutencao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricaoProduto}"));
        columnBinding.setColumnName("Descricao Produto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataInstalacao}"));
        columnBinding.setColumnName("Data Instalacao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horario}"));
        columnBinding.setColumnName("Horario");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);

        masterTable.addMouseListener(formListener);
        masterScrollPane.setViewportView(masterTable);
        masterTable.getAccessibleContext().setAccessibleParent(this);

        PanelCor.add(masterScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 105, 759, 179));

        codInstalacaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codInstalacaoLabel.setText("Cod Instalacao:");
        PanelCor.add(codInstalacaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, -1, -1));

        codCliLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codCliLabel.setText("Cod Cliente:");
        PanelCor.add(codCliLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 325, -1, -1));

        nomeClienteLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeClienteLabel.setText("Nome Cliente:");
        PanelCor.add(nomeClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 351, -1, -1));

        codFunLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codFunLabel.setText("Cod Funcionário::");
        PanelCor.add(codFunLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 377, -1, -1));

        nomeFuncionarioLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeFuncionarioLabel.setText("Nome Funcionário:");
        PanelCor.add(nomeFuncionarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 403, -1, -1));

        primeiraManutencaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        primeiraManutencaoLabel.setText("Primeira Manutenção:");
        PanelCor.add(primeiraManutencaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 429, -1, -1));

        descricaoProdutoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descricaoProdutoLabel.setText("Descrição do  Produto:");
        PanelCor.add(descricaoProdutoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 311, -1, -1));

        dataInstalacaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dataInstalacaoLabel.setText("Data Instalacao:");
        PanelCor.add(dataInstalacaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 406, -1, -1));

        horarioLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        horarioLabel.setText("Horario:");
        PanelCor.add(horarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 406, -1, -1));

        codInstalacaoField.setBackground(new java.awt.Color(204, 204, 255));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codInstalacao}"), codInstalacaoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codInstalacaoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(codInstalacaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 297, 250, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codCli}"), codCliField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codCliField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        codCliField.addActionListener(formListener);
        codCliField.addKeyListener(formListener);
        PanelCor.add(codCliField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 323, 250, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomeCliente}"), nomeClienteField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nomeClienteField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        nomeClienteField.addKeyListener(formListener);
        PanelCor.add(nomeClienteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 349, 250, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codFun}"), codFunField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codFunField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        codFunField.addKeyListener(formListener);
        PanelCor.add(codFunField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 375, 250, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomeFuncionario}"), nomeFuncionarioField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nomeFuncionarioField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        nomeFuncionarioField.addKeyListener(formListener);
        PanelCor.add(nomeFuncionarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 401, 250, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.primeiraManutencao}"), primeiraManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), primeiraManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(primeiraManutencaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 427, 250, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.descricaoProduto}"), descricaoProdutoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), descricaoProdutoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(descricaoProdutoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 332, 286, 68));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dataInstalacao}"), dataInstalacaoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), dataInstalacaoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(dataInstalacaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 427, 129, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horario}"), horarioField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), horarioField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(horarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 427, 125, -1));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar peq.png"))); // NOI18N
        saveButton.setText("Salvar");
        saveButton.addActionListener(formListener);
        PanelCor.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 465, -1, -1));

        newButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        newButton.setText("Novo cadastro");
        newButton.addActionListener(formListener);
        PanelCor.add(newButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 465, -1, -1));

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        deleteButton.setText("Deletar");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);
        PanelCor.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 465, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Instalação G.png"))); // NOI18N
        PanelCor.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Consulta de Instalações");
        PanelCor.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, -1, 40));

        lblPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPesquisar.setText("Pesquisar por:");
        PanelCor.add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, -1));

        cmbPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Nome do cliente", "Nome do funcionario"}));
        cmbPesquisar.addActionListener(formListener);
        PanelCor.add(cmbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 69, 128, -1));

        txtPesquisar.addKeyListener(formListener);
        PanelCor.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 69, 300, -1));

        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh-16.png"))); // NOI18N
        refreshButton.setText("Atualizar");
        refreshButton.addActionListener(formListener);
        PanelCor.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 465, -1, -1));

        btnGerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salario.png"))); // NOI18N
        btnGerar.setText("Gerar orçamento");
        btnGerar.setEnabled(false);
        btnGerar.addActionListener(formListener);
        PanelCor.add(btnGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 465, -1, -1));

        ConsultaInstalacao.add(PanelCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(ConsultaInstalacao, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ConsultaInstalacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.KeyListener, java.awt.event.MouseListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == btnFechar) {
                Consulta_Instalacao.this.btnFecharActionPerformed(evt);
            }
            else if (evt.getSource() == btnSalvar) {
                Consulta_Instalacao.this.btnSalvarActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                Consulta_Instalacao.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == txtInicio) {
                Consulta_Instalacao.this.txtInicioActionPerformed(evt);
            }
            else if (evt.getSource() == txtTotal) {
                Consulta_Instalacao.this.txtTotalActionPerformed(evt);
            }
            else if (evt.getSource() == txtDesconto) {
                Consulta_Instalacao.this.txtDescontoActionPerformed(evt);
            }
            else if (evt.getSource() == codCliField) {
                Consulta_Instalacao.this.codCliFieldActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                Consulta_Instalacao.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                Consulta_Instalacao.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                Consulta_Instalacao.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == cmbPesquisar) {
                Consulta_Instalacao.this.cmbPesquisarActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                Consulta_Instalacao.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == btnGerar) {
                Consulta_Instalacao.this.btnGerarActionPerformed(evt);
            }
        }

        public void keyPressed(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == codCliField) {
                Consulta_Instalacao.this.codCliFieldKeyPressed(evt);
            }
        }

        public void keyReleased(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == txtQtde) {
                Consulta_Instalacao.this.txtQtdeKeyReleased(evt);
            }
            else if (evt.getSource() == txtPreco) {
                Consulta_Instalacao.this.txtPrecoKeyReleased(evt);
            }
            else if (evt.getSource() == txtDesconto) {
                Consulta_Instalacao.this.txtDescontoKeyReleased(evt);
            }
            else if (evt.getSource() == codCliField) {
                Consulta_Instalacao.this.codCliFieldKeyReleased(evt);
            }
            else if (evt.getSource() == nomeClienteField) {
                Consulta_Instalacao.this.nomeClienteFieldKeyReleased(evt);
            }
            else if (evt.getSource() == codFunField) {
                Consulta_Instalacao.this.codFunFieldKeyReleased(evt);
            }
            else if (evt.getSource() == nomeFuncionarioField) {
                Consulta_Instalacao.this.nomeFuncionarioFieldKeyReleased(evt);
            }
            else if (evt.getSource() == txtPesquisar) {
                Consulta_Instalacao.this.txtPesquisarKeyReleased(evt);
            }
        }

        public void keyTyped(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == codCliField) {
                Consulta_Instalacao.this.codCliFieldKeyTyped(evt);
            }
            else if (evt.getSource() == txtPesquisar) {
                Consulta_Instalacao.this.txtPesquisarKeyTyped(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == masterTable) {
                Consulta_Instalacao.this.masterTableMouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String message = " Deseja realmente deletar esta instalação? ";
        String title = "Mensagem de confirmação:";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            int[] selected = masterTable.getSelectedRows();
            List<dtcc.Instalacao> toRemove = new ArrayList<dtcc.Instalacao>(selected.length);
            for (int idx = 0; idx < selected.length; idx++) {
                dtcc.Instalacao i = list.get(masterTable.convertRowIndexToModel(selected[idx]));
                toRemove.add(i);
                entityManager.remove(i);
                salvar();
            }
            list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed
    }
    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        ControleDeInstalacao LG = new ControleDeInstalacao();
        LG.setVisible(true);
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        salvar();

    }//GEN-LAST:event_saveButtonActionPerformed

    private void cmbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPesquisarActionPerformed

    //metodos usados no pesquisar!!!!!!!!!!!!!!
    public void mostraItens() {
        int seleciona = masterTable.getSelectedRow();
        codInstalacaoField.setText(masterTable.getModel().getValueAt(seleciona, 0).toString());
        codCliField.setText(masterTable.getModel().getValueAt(seleciona, 1).toString());
        nomeClienteField.setText(masterTable.getModel().getValueAt(seleciona, 2).toString());
        codFunField.setText(masterTable.getModel().getValueAt(seleciona, 3).toString());
        nomeFuncionarioField.setText(masterTable.getModel().getValueAt(seleciona, 4).toString());
        primeiraManutencaoField.setText(masterTable.getModel().getValueAt(seleciona, 5).toString());
        descricaoProdutoField.setText(masterTable.getModel().getValueAt(seleciona, 6).toString());
        dataInstalacaoField.setText(masterTable.getModel().getValueAt(seleciona, 7).toString());
        horarioField.setText(masterTable.getModel().getValueAt(seleciona, 8).toString());
    }

    public void listarCadastros() {
        String sql = "Select * from instalacao order by Cod_Instalacao Asc ";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            masterTable.setModel(DbUtils.resultSetToTableModel(rs));
            txtPesquisar.setText("");
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);

        }
    }

    public void editarCadastros() {
        String sql = "Update instalacao set  Cod_Cli  = ?, Nome_Cliente  = ?, Cod_Fun  = ?, Nome_Funcionario = ?, Primeira_Manutencao = ?, Descricao_Produto = ?, Data_Instalacao = ?, Horario = ? where Cod_Instalacao = ?";

        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, codCliField.getText());
            pst.setString(2, nomeClienteField.getText());
            pst.setString(3, codFunField.getText());
            pst.setString(4, nomeFuncionarioField.getText());
            pst.setString(5, primeiraManutencaoField.getText());
            pst.setString(6, descricaoProdutoField.getText());
            pst.setString(7, dataInstalacaoField.getText());
            pst.setString(8, horarioField.getText());
            pst.setString(9, codInstalacaoField.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso.");
            listarCadastros();

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);

        }

    }

    public void PesquisarCadastros() {
        if (cmbPesquisar.getSelectedIndex() == 0) {
            String sql = "Select Cod_Instalacao, Cod_Cli , Nome_Cliente , Cod_Fun , Nome_Funcionario, Primeira_Manutencao, Descricao_Produto, Data_Instalacao, Horario from instalacao where Nome_Cliente like ?";

            try (Connection con = conexao.getConnection()) {
                PreparedStatement pst = con.prepareStatement(sql);

                pst = con.prepareStatement(sql);
                pst.setString(1, txtPesquisar.getText() + "%");
                rs = pst.executeQuery();
                masterTable.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException error) {
                JOptionPane.showMessageDialog(null, error);
            }
        }
        if (cmbPesquisar.getSelectedIndex() == 1) {
            String sql = "Select Cod_Instalacao, Cod_Cli , Nome_Cliente , Cod_Fun , Nome_Funcionario, Primeira_Manutencao, Descricao_Produto, Data_Instalacao, Horario from instalacao where Nome_Funcionario like ?";

            try (Connection con = conexao.getConnection()) {
                PreparedStatement pst = con.prepareStatement(sql);

                pst = con.prepareStatement(sql);
                pst.setString(1, txtPesquisar.getText() + "%");
                rs = pst.executeQuery();
                masterTable.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException error) {
                JOptionPane.showMessageDialog(null, error);
            }
        }
    }

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased

        PesquisarCadastros();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        mostraItens();
        btnGerar.setEnabled(true);
        mostraItemInstalacao();
    }//GEN-LAST:event_masterTableMouseClicked

    private void mostraItemInstalacao() {
        int seleciona = masterTable.getSelectedRow();
        txtCliente.setText(masterTable.getModel().getValueAt(seleciona, 2).toString());
        txtVendedor.setText(masterTable.getModel().getValueAt(seleciona, 4).toString());
        txtCodInstalacao.setText(masterTable.getModel().getValueAt(seleciona, 0).toString());
        txtDescricao.setText(masterTable.getModel().getValueAt(seleciona, 6).toString());
    }

    private void txtPesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarKeyTyped

    private void codCliFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codCliFieldKeyReleased
        pegaNomeCli();
    }//GEN-LAST:event_codCliFieldKeyReleased

    private void codCliFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codCliFieldKeyPressed

    }//GEN-LAST:event_codCliFieldKeyPressed

    public void pegaNomeCli() {
        String sql = "select Nome from cad_cliente where Cod_Cli = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, codCliField.getText());
            rs = pst.executeQuery();
            rs.first();
            nomeClienteField.setText(rs.getString("Nome"));
        } catch (SQLException error) {

        }
    }

    public void pegaNomeFun() {
        String sql = "select Nome from cad_funcionario where Cod_Fun = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, codFunField.getText());
            rs = pst.executeQuery();
            rs.first();
            nomeFuncionarioField.setText(rs.getString("Nome"));
        } catch (SQLException error) {

        }

    }

    private void codCliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codCliFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codCliFieldActionPerformed

    private void codCliFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codCliFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_codCliFieldKeyTyped

    private void nomeFuncionarioFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeFuncionarioFieldKeyReleased
        pegaCodFun();
    }//GEN-LAST:event_nomeFuncionarioFieldKeyReleased

    private void nomeClienteFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeClienteFieldKeyReleased
        pegaCodCli();
    }//GEN-LAST:event_nomeClienteFieldKeyReleased

    private void codFunFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codFunFieldKeyReleased
        pegaNomeFun();        // TODO add your handling code here:
    }//GEN-LAST:event_codFunFieldKeyReleased

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        atualizar();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        ConsultaInstalacao.setVisible(true);
        GerarOrcamento.setVisible(true);
    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        ConsultaInstalacao.setVisible(true);
        GerarOrcamento.setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if ((txtCliente.getText().isEmpty()) || (txtVendedor.getText().isEmpty()) || (txtAno.getText().isEmpty()) || (txtInicio.getText().equals("  /  /    ")) || (txtFim.getText().equals("  /  /    "))) {
            JOptionPane.showMessageDialog(null, "Alguns campos não podem retornar vazios");

        } else {
            pegaInformacoesDosCampos();
            od.inserirOrcamentos(ob);
            JOptionPane.showMessageDialog(null, "Orçamento cadastrado com sucesso! ", "Aviso", 1);
            apagarCampos();
        }                 // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limparCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicioActionPerformed

    private void txtQtdeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdeKeyReleased
        calculaValor();         // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdeKeyReleased

    private void txtPrecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoKeyReleased
        calculaValor();         // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoKeyReleased

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed

    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescontoActionPerformed

    private void txtDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyReleased
        calculaValor();        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescontoKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane ConsultaInstalacao;
    private javax.swing.JInternalFrame GerarOrcamento;
    private javax.swing.JPanel PanelCor;
    private javax.swing.JComboBox Status;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbPesquisar;
    private javax.swing.JTextField codCliField;
    private javax.swing.JLabel codCliLabel;
    private javax.swing.JTextField codFunField;
    private javax.swing.JLabel codFunLabel;
    private javax.swing.JTextField codInstalacaoField;
    private javax.swing.JLabel codInstalacaoLabel;
    private javax.swing.JTextField dataInstalacaoField;
    private javax.swing.JLabel dataInstalacaoLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descricaoProdutoField;
    private javax.swing.JLabel descricaoProdutoLabel;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTextField horarioField;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPesquisar;
    private java.util.List<dtcc.Instalacao> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField nomeClienteField;
    private javax.swing.JLabel nomeClienteLabel;
    private javax.swing.JTextField nomeFuncionarioField;
    private javax.swing.JLabel nomeFuncionarioLabel;
    private javax.swing.JTextField primeiraManutencaoField;
    private javax.swing.JLabel primeiraManutencaoLabel;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JFormattedTextField txtAno;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodInstalacao;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JFormattedTextField txtFim;
    private javax.swing.JFormattedTextField txtInicio;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JFormattedTextField txtPreco;
    private javax.swing.JFormattedTextField txtQtde;
    private javax.swing.JFormattedTextField txtTotal;
    private javax.swing.JTextField txtVendedor;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public void run() {
        JFrame frame = new JFrame("Consulta de Instalações");
        frame.setContentPane(new Consulta_Instalacao());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);        // TODO add your handling code here:

    }

    ;
    

    private void pegaCodCli() {
        String sql = "select Cod_Cli from cad_cliente where Nome = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, nomeClienteField.getText());
            rs = pst.executeQuery();
            rs.first();
            codCliField.setText(rs.getString("Cod_Cli"));
        } catch (SQLException error) {

        }

    }

    private void pegaCodFun() {
        String sql = "select Cod_Fun from cad_funcionario where Nome = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, nomeFuncionarioField.getText());
            rs = pst.executeQuery();
            rs.first();
            codFunField.setText(rs.getString("Cod_Fun"));
        } catch (SQLException error) {

        }
    }

    private void salvar() {
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
            editarCadastros();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<dtcc.Instalacao> merged = new ArrayList<dtcc.Instalacao>(list.size());
            for (dtcc.Instalacao i : list) {
                merged.add(entityManager.merge(i));
                atualizar();
            }
        }
    }

    private void atualizar() {
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
            btnGerar.setEnabled(false);
        }
        list.clear();
        list.addAll(data);
        listarCadastros();
    }

    private void calculaValor() {
        Double preco = Double.parseDouble(txtPreco.getText());
        Double desconto = Double.parseDouble(txtDesconto.getText());
        Double qtde = Double.parseDouble(txtQtde.getText());
        Double resultado = preco * qtde - desconto;
        String result = Double.toString(resultado);
        txtTotal.setText(result);
    }

    private void apagarCampos() {
        Status.setSelectedIndex(0);
        txtCliente.setText("");
        txtVendedor.setText("");
        txtAno.setText("");
        txtInicio.setText("");
        txtFim.setText("");
        txtDescricao.setText("");
        txtDesconto.setText("");
        txtPreco.setText("");
        txtTotal.setText("");
        txtQtde.setText("");

    }

    private void limparCampos() {
        String message = " Deseja realmente criar um novo orçamento? ";
        String title = "Novo Orçamento";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            apagarCampos();

        }
    }

    private void pegaInformacoesDosCampos() {
        ob = new OrcamentosBean();

        ob.setStatus(Status.getSelectedIndex());
        ob.setTxtCliente(txtCliente.getText());
        ob.setTxtVendedor(txtVendedor.getText());
        ob.setTxtAno(txtAno.getText());
        ob.setTxtInicio(txtInicio.getText());
        ob.setTxtFim(txtFim.getText());
        ob.setTxtDescricao(txtDescricao.getText());
        ob.setTxtDesconto(txtDesconto.getText());
        ob.setTxtPreco(txtPreco.getText());
        ob.setTxtTotal(txtTotal.getText());
        ob.setTxtQtde(txtQtde.getText());
    }

    private void geraOrcamento() {
        try (Connection con = conexao.getConnection()) {
            String sql = "Select Nome_Cliente, Nome_Funcionario, Descricao_Produto from instalacao where Cod_Instalacao = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtCodInstalacao.getText() + "%");
            rs = pst.executeQuery();
            rs.first();
            txtCliente.setText(rs.getString("Nome_Cliente"));
            txtVendedor.setText(rs.getString("Nome_Funcionario"));
            txtDescricao.setText(rs.getString("Descricao_Produto"));

        } catch (SQLException error) {

        }
    }
}
