/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtcc;

import BancoDeDados.conexao;
import java.awt.EventQueue;
import java.beans.Beans;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
import java.awt.Desktop;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author JoãoVitor
 */
public class Consulta_Produtos extends JPanel {

    ResultSet rs;

    public Consulta_Produtos() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
            java.util.Collection data = query.getResultList();
            for (Object entity : data) {
                entityManager.refresh(entity);
            }
            list.clear();
            list.addAll(data);
            listarCadastros();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("bd?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM CadProdutos c");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        ConsultaProduto = new javax.swing.JDesktopPane();
        PainelCor = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        codProdLabel = new javax.swing.JLabel();
        codParteLabel = new javax.swing.JLabel();
        statusProdLabel = new javax.swing.JLabel();
        quantidadeLabel = new javax.swing.JLabel();
        fabricanteLabel = new javax.swing.JLabel();
        referenciaLabel = new javax.swing.JLabel();
        fornecedorLabel = new javax.swing.JLabel();
        modeloLabel = new javax.swing.JLabel();
        capacidadeLabel = new javax.swing.JLabel();
        codProdField = new javax.swing.JTextField();
        codParteField = new javax.swing.JTextField();
        statusProdField = new javax.swing.JTextField();
        quantidadeField = new javax.swing.JTextField();
        fabricanteField = new javax.swing.JTextField();
        referenciaField = new javax.swing.JTextField();
        fornecedorField = new javax.swing.JTextField();
        modeloField = new javax.swing.JTextField();
        capacidadeField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        cmbPesquisar = new javax.swing.JComboBox();
        txtPesquisar = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        btnInternet = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        btnTirar1 = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();
        MaisDetalhes = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        icmsField = new javax.swing.JTextField();
        ncmField = new javax.swing.JTextField();
        grupoField = new javax.swing.JTextField();
        faixaDePreco2Field = new javax.swing.JTextField();
        faixaDePrecoField = new javax.swing.JTextField();
        descricaoField = new javax.swing.JTextField();
        csosnField = new javax.swing.JTextField();
        stField = new javax.swing.JTextField();
        icmsLabel = new javax.swing.JLabel();
        csosnLabel = new javax.swing.JLabel();
        stLabel = new javax.swing.JLabel();
        ncmLabel = new javax.swing.JLabel();
        grupoLabel = new javax.swing.JLabel();
        faixaDePreco2Label = new javax.swing.JLabel();
        faixaDePrecoLabel = new javax.swing.JLabel();
        descricaoLabel = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        ConsultaProduto.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelCor.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codProd}"));
        columnBinding.setColumnName("Cod Prod");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${st}"));
        columnBinding.setColumnName("St");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${csosn}"));
        columnBinding.setColumnName("Csosn");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codParte}"));
        columnBinding.setColumnName("Cod Parte");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${statusProd}"));
        columnBinding.setColumnName("Status Prod");
        columnBinding.setColumnClass(Short.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidade}"));
        columnBinding.setColumnName("Quantidade");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fabricante}"));
        columnBinding.setColumnName("Fabricante");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${referencia}"));
        columnBinding.setColumnName("Referencia");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fornecedor}"));
        columnBinding.setColumnName("Fornecedor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${modelo}"));
        columnBinding.setColumnName("Modelo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capacidade}"));
        columnBinding.setColumnName("Capacidade");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Descricao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${faixaDePreco}"));
        columnBinding.setColumnName("Faixa De Preco");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${faixaDePreco2}"));
        columnBinding.setColumnName("Faixa De Preco2");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${grupo}"));
        columnBinding.setColumnName("Grupo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ncm}"));
        columnBinding.setColumnName("Ncm");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${icms}"));
        columnBinding.setColumnName("Icms");
        columnBinding.setColumnClass(Float.class);
        bindingGroup.addBinding(jTableBinding);

        masterTable.addMouseListener(formListener);
        masterScrollPane.setViewportView(masterTable);

        codProdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codProdLabel.setText("Cod Prod:");

        codParteLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codParteLabel.setText("Cod Parte:");

        statusProdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusProdLabel.setText("Status :");

        quantidadeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quantidadeLabel.setText("Quantidade:");

        fabricanteLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fabricanteLabel.setText("Fabricante:");

        referenciaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        referenciaLabel.setText("Referencia:");

        fornecedorLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fornecedorLabel.setText("Fornecedor:");

        modeloLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modeloLabel.setText("Modelo:");

        capacidadeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        capacidadeLabel.setText("Capacidade:");

        codProdField.setEditable(false);
        codProdField.setBackground(new java.awt.Color(204, 204, 255));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codProd}"), codProdField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codProdField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codParte}"), codParteField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codParteField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.statusProd}"), statusProdField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), statusProdField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.quantidade}"), quantidadeField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), quantidadeField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.fabricante}"), fabricanteField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), fabricanteField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.referencia}"), referenciaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), referenciaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.fornecedor}"), fornecedorField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), fornecedorField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.modelo}"), modeloField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), modeloField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.capacidade}"), capacidadeField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), capacidadeField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar peq.png"))); // NOI18N
        saveButton.setText("Salvar");
        saveButton.setEnabled(false);
        saveButton.addActionListener(formListener);

        newButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        newButton.setText("Novo cadastro");
        newButton.addActionListener(formListener);

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        deleteButton.setText("Deletar");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Consulta de Produtos");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Produtos.png"))); // NOI18N

        lblPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPesquisar.setText("Pesquisar por:");

        cmbPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Modelo"}));
        cmbPesquisar.addActionListener(formListener);

        txtPesquisar.addKeyListener(formListener);

        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh-16.png"))); // NOI18N
        refreshButton.setText("Atualizar");
        refreshButton.addActionListener(formListener);

        lblImagem.setText("     ");
        lblImagem.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagem.setMaximumSize(new java.awt.Dimension(0, 0));
        lblImagem.setMinimumSize(new java.awt.Dimension(0, 0));

        btnRemover.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        btnRemover.setEnabled(false);
        btnRemover.addActionListener(formListener);

        btnInternet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Internet.png"))); // NOI18N
        btnInternet.setEnabled(false);
        btnInternet.addActionListener(formListener);

        btnSelecionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pasta de foto.png"))); // NOI18N
        btnSelecionar.setEnabled(false);
        btnSelecionar.addActionListener(formListener);

        btnTirar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTirar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Webcam.png"))); // NOI18N
        btnTirar1.setEnabled(false);
        btnTirar1.addActionListener(formListener);

        btnMais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        btnMais.setText("Mais detalhes");
        btnMais.setEnabled(false);
        btnMais.addActionListener(formListener);

        javax.swing.GroupLayout PainelCorLayout = new javax.swing.GroupLayout(PainelCor);
        PainelCor.setLayout(PainelCorLayout);
        PainelCorLayout.setHorizontalGroup(
            PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCorLayout.createSequentialGroup()
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelCorLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRemover)
                                    .addComponent(btnTirar1)
                                    .addComponent(btnSelecionar)))
                            .addGroup(PainelCorLayout.createSequentialGroup()
                                .addComponent(lblPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(btnInternet)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(PainelCorLayout.createSequentialGroup()
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PainelCorLayout.createSequentialGroup()
                                    .addComponent(newButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(refreshButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deleteButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(saveButton))
                                .addGroup(PainelCorLayout.createSequentialGroup()
                                    .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(codProdLabel)
                                        .addComponent(codParteLabel)
                                        .addComponent(statusProdLabel)
                                        .addComponent(quantidadeLabel)
                                        .addComponent(fornecedorLabel))
                                    .addGap(26, 26, 26)
                                    .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(codParteField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(statusProdField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(quantidadeField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fornecedorField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(codProdField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(59, 59, 59)
                                    .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fabricanteField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMais, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCorLayout.createSequentialGroup()
                                            .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(modeloLabel)
                                                .addComponent(referenciaLabel)
                                                .addComponent(capacidadeLabel)
                                                .addComponent(fabricanteLabel))
                                            .addGap(18, 18, 18)
                                            .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(modeloField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(referenciaField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(capacidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel19)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel9)
                    .addContainerGap(660, Short.MAX_VALUE)))
        );
        PainelCorLayout.setVerticalGroup(
            PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCorLayout.createSequentialGroup()
                        .addComponent(btnTirar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInternet)
                            .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPesquisar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover))
                    .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCorLayout.createSequentialGroup()
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fabricanteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fabricanteLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(referenciaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(referenciaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modeloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modeloLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacidadeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMais))
                    .addGroup(PainelCorLayout.createSequentialGroup()
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codProdField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codProdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codParteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codParteLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusProdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusProdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantidadeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fornecedorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fornecedorLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(deleteButton)
                    .addComponent(newButton)
                    .addComponent(refreshButton))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PainelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        ConsultaProduto.add(PainelCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        MaisDetalhes.setBackground(new java.awt.Color(255, 255, 255));
        MaisDetalhes.setTitle("Mais detalhes");
        MaisDetalhes.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/dtcc/iconframe.png"))); // NOI18N
        MaisDetalhes.setMinimumSize(new java.awt.Dimension(518, 302));
        try {
            MaisDetalhes.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        MaisDetalhes.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair peq.png"))); // NOI18N
        jButton2.setText("Fechar");
        jButton2.addActionListener(formListener);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 26));
        jPanel1.add(icmsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 330, -1));
        jPanel1.add(ncmField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 330, -1));
        jPanel1.add(grupoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 330, -1));

        faixaDePreco2Field.addActionListener(formListener);
        jPanel1.add(faixaDePreco2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 150, -1));
        jPanel1.add(faixaDePrecoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, -1));
        jPanel1.add(descricaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 330, 66));
        jPanel1.add(csosnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 11, 120, -1));
        jPanel1.add(stField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 100, -1));

        icmsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        icmsLabel.setText("Icms:");
        jPanel1.add(icmsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 169, 18));

        csosnLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        csosnLabel.setText("Csosn:");
        jPanel1.add(csosnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 20));

        stLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stLabel.setText("St:");
        jPanel1.add(stLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 20, 20));

        ncmLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ncmLabel.setText("Ncm:");
        jPanel1.add(ncmLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 166, 20));

        grupoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grupoLabel.setText("Grupo:");
        jPanel1.add(grupoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 178, 20));

        faixaDePreco2Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        faixaDePreco2Label.setText("à:");
        jPanel1.add(faixaDePreco2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 20));

        faixaDePrecoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        faixaDePrecoLabel.setText("Faixa De Preco:");
        jPanel1.add(faixaDePrecoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 229, 20));

        descricaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descricaoLabel.setText("Descricao:");
        jPanel1.add(descricaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 224, 16));

        javax.swing.GroupLayout MaisDetalhesLayout = new javax.swing.GroupLayout(MaisDetalhes.getContentPane());
        MaisDetalhes.getContentPane().setLayout(MaisDetalhesLayout);
        MaisDetalhesLayout.setHorizontalGroup(
            MaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MaisDetalhesLayout.setVerticalGroup(
            MaisDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ConsultaProduto.add(MaisDetalhes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 289));
        ConsultaProduto.setLayer(MaisDetalhes, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ConsultaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ConsultaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.KeyListener, java.awt.event.MouseListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == saveButton) {
                Consulta_Produtos.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                Consulta_Produtos.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                Consulta_Produtos.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == cmbPesquisar) {
                Consulta_Produtos.this.cmbPesquisarActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                Consulta_Produtos.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == btnRemover) {
                Consulta_Produtos.this.btnRemoverActionPerformed(evt);
            }
            else if (evt.getSource() == btnInternet) {
                Consulta_Produtos.this.btnInternetActionPerformed(evt);
            }
            else if (evt.getSource() == btnSelecionar) {
                Consulta_Produtos.this.btnSelecionarActionPerformed(evt);
            }
            else if (evt.getSource() == btnTirar1) {
                Consulta_Produtos.this.btnTirar1ActionPerformed(evt);
            }
            else if (evt.getSource() == btnMais) {
                Consulta_Produtos.this.btnMaisActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                Consulta_Produtos.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == faixaDePreco2Field) {
                Consulta_Produtos.this.faixaDePreco2FieldActionPerformed(evt);
            }
        }

        public void keyPressed(java.awt.event.KeyEvent evt) {
        }

        public void keyReleased(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == txtPesquisar) {
                Consulta_Produtos.this.txtPesquisarKeyReleased(evt);
            }
        }

        public void keyTyped(java.awt.event.KeyEvent evt) {
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == masterTable) {
                Consulta_Produtos.this.masterTableMouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String message = " Deseja realmente deletar este produto? ";
        String title = "Mensagem de confirmação:";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            int[] selected = masterTable.getSelectedRows();
            List<dtcc.CadProdutos> toRemove = new ArrayList<dtcc.CadProdutos>(selected.length);
            for (int idx = 0; idx < selected.length; idx++) {
                dtcc.CadProdutos c = list.get(masterTable.convertRowIndexToModel(selected[idx]));
                toRemove.add(c);
                entityManager.remove(c);
                salvar();
            }
            list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed
    }
    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        CadProduto LG = new CadProduto();
        LG.setVisible(true);
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        salvar();
        lblImagem.setIcon(null);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cmbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPesquisarActionPerformed

    //metodos usados no pesquisar!!!!!!!!!!!!!!
    public void mostraItens() {
        int seleciona = masterTable.getSelectedRow();
        codProdField.setText(masterTable.getModel().getValueAt(seleciona, 0).toString());
        stField.setText(masterTable.getModel().getValueAt(seleciona, 1).toString());
        csosnField.setText(masterTable.getModel().getValueAt(seleciona, 2).toString());
        codParteField.setText(masterTable.getModel().getValueAt(seleciona, 3).toString());
        statusProdField.setText(masterTable.getModel().getValueAt(seleciona, 4).toString());
        quantidadeField.setText(masterTable.getModel().getValueAt(seleciona, 5).toString());
        fabricanteField.setText(masterTable.getModel().getValueAt(seleciona, 6).toString());
        referenciaField.setText(masterTable.getModel().getValueAt(seleciona, 7).toString());
        fornecedorField.setText(masterTable.getModel().getValueAt(seleciona, 8).toString());
        modeloField.setText(masterTable.getModel().getValueAt(seleciona, 9).toString());
        capacidadeField.setText(masterTable.getModel().getValueAt(seleciona, 10).toString());
        descricaoField.setText(masterTable.getModel().getValueAt(seleciona, 11).toString());
        faixaDePrecoField.setText(masterTable.getModel().getValueAt(seleciona, 12).toString());
        faixaDePreco2Field.setText(masterTable.getModel().getValueAt(seleciona, 13).toString());
        grupoField.setText(masterTable.getModel().getValueAt(seleciona, 14).toString());
        ncmField.setText(masterTable.getModel().getValueAt(seleciona, 15).toString());
        icmsField.setText(masterTable.getModel().getValueAt(seleciona, 16).toString());
    }

    public void listarCadastros() {
        String sql = "Select Cod_Prod,ST, CSOSN, Cod_Parte, Status_Prod, Quantidade, Fabricante, Referencia, Fornecedor , Modelo, Capacidade, Descricao , Faixa_De_Preco , Faixa_De_Preco2 , Grupo , NCM , ICMS from cad_produtos order by Cod_Prod Asc ";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            masterTable.setModel(DbUtils.resultSetToTableModel(rs));
            txtPesquisar.setText("");
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);

        }
    }

    public void editarCadastros() {
        String sql = "Update cad_produtos set  ST  = ?, CSOSN  = ?, Cod_Parte  = ?, Status_Prod = ?, Quantidade = ?, Fabricante = ?, Referencia = ?, Fornecedor = ? , Modelo =?, Capacidade=?, Descricao =?, Faixa_De_Preco =?, Faixa_De_Preco2 =?, Grupo =?, NCM =?, ICMS =?, Foto_Prod=? where Cod_Prod = ?";

        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, stField.getText());
            pst.setString(2, csosnField.getText());
            pst.setString(3, codParteField.getText());
            pst.setString(4, statusProdField.getText());
            pst.setString(5, quantidadeField.getText());
            pst.setString(6, fabricanteField.getText());
            pst.setString(7, referenciaField.getText());
            pst.setString(8, fornecedorField.getText());
            pst.setString(9, modeloField.getText());
            pst.setString(10, capacidadeField.getText());
            pst.setString(11, descricaoField.getText());
            pst.setString(12, faixaDePrecoField.getText());
            pst.setString(13, faixaDePreco2Field.getText());
            pst.setString(14, grupoField.getText());
            pst.setString(15, ncmField.getText());
            pst.setString(16, icmsField.getText());
            pst.setString(17, caminhoDaImagem);
            pst.setString(18, codProdField.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso.");
            listarCadastros();

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);

        }

    }

    public void PesquisarCadastros() {
        if (cmbPesquisar.getSelectedIndex() == 0) {
            String sql = "Select Cod_Prod,ST, CSOSN, Cod_Parte, Status_Prod, Quantidade, Fabricante, Referencia, Fornecedor , Modelo, Capacidade, Descricao , Faixa_De_Preco , Faixa_De_Preco2 , Grupo , NCM , ICMS from cad_produtos where Modelo like ?";

            try (Connection con = conexao.getConnection()) {
                PreparedStatement pst = con.prepareStatement(sql);

                pst = con.prepareStatement(sql);
                pst.setString(1, txtPesquisar.getText() + "%");
                rs = pst.executeQuery();
                masterTable.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException error) {
                JOptionPane.showMessageDialog(null, error);
            }
        }
    }

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased

        PesquisarCadastros();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        mostraItens();
        consultaImagem();
        btnTirar1.setEnabled(true);
        btnSelecionar.setEnabled(true);
        btnInternet.setEnabled(true);
        btnRemover.setEnabled(true);
        saveButton.setEnabled(true);
        btnMais.setEnabled(true);
    }//GEN-LAST:event_masterTableMouseClicked

    private void consultaImagem() {
        String sql = "select Foto_Prod from cad_produtos where Cod_Prod = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, codProdField.getText());
            rs = pst.executeQuery();
            rs.first();

            String file = rs.getString("Foto_Prod");
            lblImagem.setIcon(new ImageIcon(file));
            ImageIcon icon = new ImageIcon(file);
            Image img = icon.getImage();
            Image newImg = img.getScaledInstance(121, 123, java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImg);
            lblImagem.setIcon(newIcon);
            lblImagem.setSize(104, 14);
            caminhoDaImagem = file;
        } catch (SQLException error) {

        }
    }

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        atualizar();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        lblImagem.setIcon(null);
        caminhoDaImagem = "";
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternetActionPerformed
        Desktop desk = java.awt.Desktop.getDesktop();
        try {
            desk.browse(new java.net.URI("https://www.google.com.br/imghp?hl=pt-BR&tab=wi&ei=hFvtUqmWLIjskQePxoDADQ&ved=0CAQQqi4oAg//"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnInternetActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed

        BancoDeDados.ProdutoBean p = new BancoDeDados.ProdutoBean();
        p.setImagem(this.retornacaminho());
    }//GEN-LAST:event_btnSelecionarActionPerformed

    String caminhoDaImagem;

    private String retornacaminho() throws java.lang.NullPointerException {
        String file = "";
        JFileChooser dlg = new JFileChooser();
        int opcion = dlg.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            file += dlg.getSelectedFile().getPath();
            lblImagem.setIcon(new ImageIcon(file));
            ImageIcon icon = new ImageIcon(file);
            Image img = icon.getImage();
            Image newImg = img.getScaledInstance(121, 123, java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImg);        // TODO add your handling code here:
            lblImagem.setIcon(newIcon);
            lblImagem.setSize(104, 14);
            caminhoDaImagem = file;

            //   System.out.println("Caminho do arquivo : "+file);
        }
        return file;
    }

    private void btnTirar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTirar1ActionPerformed
        Form_webcam LG = new Form_webcam();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTirar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ConsultaProduto.setVisible(true);
        MaisDetalhes.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void faixaDePreco2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faixaDePreco2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faixaDePreco2FieldActionPerformed

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisActionPerformed
        ConsultaProduto.setVisible(true);
        MaisDetalhes.setVisible(true);
    }//GEN-LAST:event_btnMaisActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane ConsultaProduto;
    private javax.swing.JInternalFrame MaisDetalhes;
    private javax.swing.JPanel PainelCor;
    private javax.swing.JButton btnInternet;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnTirar1;
    private javax.swing.JTextField capacidadeField;
    private javax.swing.JLabel capacidadeLabel;
    private javax.swing.JComboBox cmbPesquisar;
    private javax.swing.JTextField codParteField;
    private javax.swing.JLabel codParteLabel;
    private javax.swing.JTextField codProdField;
    private javax.swing.JLabel codProdLabel;
    private javax.swing.JTextField csosnField;
    private javax.swing.JLabel csosnLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descricaoField;
    private javax.swing.JLabel descricaoLabel;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTextField fabricanteField;
    private javax.swing.JLabel fabricanteLabel;
    private javax.swing.JTextField faixaDePreco2Field;
    private javax.swing.JLabel faixaDePreco2Label;
    private javax.swing.JTextField faixaDePrecoField;
    private javax.swing.JLabel faixaDePrecoLabel;
    private javax.swing.JTextField fornecedorField;
    private javax.swing.JLabel fornecedorLabel;
    private javax.swing.JTextField grupoField;
    private javax.swing.JLabel grupoLabel;
    private javax.swing.JTextField icmsField;
    private javax.swing.JLabel icmsLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblPesquisar;
    private java.util.List<dtcc.CadProdutos> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JTextField modeloField;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JTextField ncmField;
    private javax.swing.JLabel ncmLabel;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField quantidadeField;
    private javax.swing.JLabel quantidadeLabel;
    private javax.persistence.Query query;
    private javax.swing.JTextField referenciaField;
    private javax.swing.JLabel referenciaLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField stField;
    private javax.swing.JLabel stLabel;
    private javax.swing.JTextField statusProdField;
    private javax.swing.JLabel statusProdLabel;
    private javax.swing.JTextField txtPesquisar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public void run() {
        JFrame frame = new JFrame("Consulta de Produtos");
        frame.setContentPane(new Consulta_Produtos());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);

    }

    ;
    

    private void salvar() {
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
            editarCadastros();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<dtcc.CadProdutos> merged = new ArrayList<dtcc.CadProdutos>(list.size());
            for (dtcc.CadProdutos c : list) {
                merged.add(entityManager.merge(c));
                atualizar();
            }
        }
    }

    private void atualizar() {
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
            btnTirar1.setEnabled(false);
            btnSelecionar.setEnabled(false);
            btnInternet.setEnabled(false);
            btnRemover.setEnabled(false);
            saveButton.setEnabled(false);
            btnMais.setEnabled(false);
            lblImagem.setIcon(null);
        }
        list.clear();
        list.addAll(data);
        listarCadastros();
    }

    private void alteraImagem() {
        String sql = "Update cad_cliente set Foto= ? where Cod_Cli = ?";

        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, caminhoDaImagem);
            pst.setString(2, codProdField.getText());
            pst.executeUpdate();
            listarCadastros();

        } catch (SQLException error) {

        }

    }

}
