/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtcc;

import BancoDeDados.OrcamentosBean;
import BancoDeDados.OrcamentosDao;
import BancoDeDados.conexao;
import java.awt.EventQueue;
import java.beans.Beans;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JoãoVitor
 */
public class Consulta_Manutencao extends JPanel {

    ResultSet rs;
    private DefaultTableModel DefaultTableModel;
    OrcamentosDao od = new OrcamentosDao();
    OrcamentosBean ob;

    public Consulta_Manutencao() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
            java.util.Collection data = query.getResultList();
            for (Object entity : data) {
                entityManager.refresh(entity);
            }
            list.clear();
            list.addAll(data);
            listarCadastros();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("bd?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Manutencao m");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        ConsultaManutencao = new javax.swing.JDesktopPane();
        GerarOrcamento = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtAno = new javax.swing.JFormattedTextField();
        txtFim = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Status = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JFormattedTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQtde = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JFormattedTextField();
        txtTotal = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCodManutencao = new javax.swing.JTextField();
        PanelCor = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        codManutencaoLabel = new javax.swing.JLabel();
        tipoManutencaoLabel = new javax.swing.JLabel();
        descricaoDoProdutoLabel = new javax.swing.JLabel();
        ultimaManutencaoLabel = new javax.swing.JLabel();
        proximaManutencaoLabel = new javax.swing.JLabel();
        descricaoDoProblemaLabel = new javax.swing.JLabel();
        nomeFuncionarioLabel = new javax.swing.JLabel();
        nomeClienteLabel = new javax.swing.JLabel();
        codCliLabel = new javax.swing.JLabel();
        codFunLabel = new javax.swing.JLabel();
        codManutencaoField = new javax.swing.JTextField();
        tipoManutencaoField = new javax.swing.JTextField();
        descricaoDoProdutoField = new javax.swing.JTextField();
        ultimaManutencaoField = new javax.swing.JTextField();
        proximaManutencaoField = new javax.swing.JTextField();
        descricaoDoProblemaField = new javax.swing.JTextField();
        nomeFuncionarioField = new javax.swing.JTextField();
        nomeClienteField = new javax.swing.JTextField();
        codCliField = new javax.swing.JTextField();
        codFunField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        cmbPesquisar = new javax.swing.JComboBox();
        txtPesquisar = new javax.swing.JTextField();
        refreshButton1 = new javax.swing.JButton();
        btnGerar = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(255, 255, 255));

        ConsultaManutencao.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaManutencao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GerarOrcamento.setTitle("Orçamentos De Manutenção");
        GerarOrcamento.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/dtcc/iconframe.png"))); // NOI18N
        GerarOrcamento.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salario grande.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Orçamentos De Manutenção");

        btnFechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair peq.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(formListener);

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar peq.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(formListener);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Status:");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        jButton2.setText("Novo Orçamento");
        jButton2.addActionListener(formListener);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cliente:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Vendedor:");

        try {
            txtFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Orçamento n°");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ano:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Inicio:");

        Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0- Disponivel", "1- Indisponivel"}));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Fim:");

        try {
            txtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtInicio.addActionListener(formListener);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 255));
        txtCodigo.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Qtde:");

        txtQtde.addKeyListener(formListener);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Preço Uni:");

        txtPreco.addKeyListener(formListener);

        txtTotal.addActionListener(formListener);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Total:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Descrição:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Desconto:");

        txtDesconto.addActionListener(formListener);
        txtDesconto.addKeyListener(formListener);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Cod Manutenção:");

        txtCodManutencao.setEditable(false);
        txtCodManutencao.setBackground(new java.awt.Color(204, 204, 255));
        txtCodManutencao.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addGap(6, 6, 6)
                        .addComponent(btnFechar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodManutencao))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar)
                        .addComponent(jButton2))
                    .addComponent(btnFechar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout GerarOrcamentoLayout = new javax.swing.GroupLayout(GerarOrcamento.getContentPane());
        GerarOrcamento.getContentPane().setLayout(GerarOrcamentoLayout);
        GerarOrcamentoLayout.setHorizontalGroup(
            GerarOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GerarOrcamentoLayout.setVerticalGroup(
            GerarOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ConsultaManutencao.add(GerarOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 780, 280));

        PanelCor.setBackground(new java.awt.Color(255, 255, 255));
        PanelCor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codManutencao}"));
        columnBinding.setColumnName("Cod Manutencao");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codCli}"));
        columnBinding.setColumnName("Cod Cli");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeCliente}"));
        columnBinding.setColumnName("Nome Cliente");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codFun}"));
        columnBinding.setColumnName("Cod Fun");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeFuncionario}"));
        columnBinding.setColumnName("Nome Funcionario");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ultimaManutencao}"));
        columnBinding.setColumnName("Ultima Manutencao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${proximaManutencao}"));
        columnBinding.setColumnName("Proxima Manutencao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipoManutencao}"));
        columnBinding.setColumnName("Tipo Manutencao");
        columnBinding.setColumnClass(Short.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricaoDoProduto}"));
        columnBinding.setColumnName("Descricao Do Produto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricaoDoProblema}"));
        columnBinding.setColumnName("Descricao Do Problema");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterTable.addMouseListener(formListener);
        masterScrollPane.setViewportView(masterTable);

        PanelCor.add(masterScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, 840, 164));

        codManutencaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codManutencaoLabel.setText("Cod Manutencao:");
        PanelCor.add(codManutencaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 281, -1, -1));

        tipoManutencaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipoManutencaoLabel.setText("Tipo Manutencao:");
        PanelCor.add(tipoManutencaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        descricaoDoProdutoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descricaoDoProdutoLabel.setText("Descricao Do Produto:");
        PanelCor.add(descricaoDoProdutoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 310, -1, 20));

        ultimaManutencaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ultimaManutencaoLabel.setText("Ultima Manutencao:");
        PanelCor.add(ultimaManutencaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        proximaManutencaoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        proximaManutencaoLabel.setText("Proxima Manutencao:");
        PanelCor.add(proximaManutencaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        descricaoDoProblemaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descricaoDoProblemaLabel.setText("Descricao Do Problema:");
        PanelCor.add(descricaoDoProblemaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 370, -1, 20));

        nomeFuncionarioLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeFuncionarioLabel.setText("Nome do Funcionario:");
        PanelCor.add(nomeFuncionarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        nomeClienteLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeClienteLabel.setText("Nome do Cliente:");
        PanelCor.add(nomeClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 338, -1, -1));

        codCliLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codCliLabel.setText("Código do Cliente:");
        PanelCor.add(codCliLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 312, -1, -1));

        codFunLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codFunLabel.setText("Código do Funcionario:");
        PanelCor.add(codFunLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 364, -1, -1));

        codManutencaoField.setEditable(false);
        codManutencaoField.setBackground(new java.awt.Color(204, 204, 255));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codManutencao}"), codManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(codManutencaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 279, 240, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.tipoManutencao}"), tipoManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), tipoManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(tipoManutencaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 290, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.descricaoDoProduto}"), descricaoDoProdutoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), descricaoDoProdutoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(descricaoDoProdutoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 310, 290, 46));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ultimaManutencao}"), ultimaManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ultimaManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(ultimaManutencaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.proximaManutencao}"), proximaManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), proximaManutencaoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(proximaManutencaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 150, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.descricaoDoProblema}"), descricaoDoProblemaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), descricaoDoProblemaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        PanelCor.add(descricaoDoProblemaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 370, 291, 46));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomeFuncionario}"), nomeFuncionarioField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nomeFuncionarioField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        nomeFuncionarioField.addKeyListener(formListener);
        PanelCor.add(nomeFuncionarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 388, 240, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomeCliente}"), nomeClienteField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nomeClienteField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        nomeClienteField.addKeyListener(formListener);
        PanelCor.add(nomeClienteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 336, 240, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codCli}"), codCliField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codCliField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        codCliField.addKeyListener(formListener);
        PanelCor.add(codCliField, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 310, 240, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codFun}"), codFunField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codFunField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        codFunField.addKeyListener(formListener);
        PanelCor.add(codFunField, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 362, 240, -1));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar peq.png"))); // NOI18N
        saveButton.setText("Salvar");
        saveButton.addActionListener(formListener);
        PanelCor.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 476, -1, -1));

        newButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        newButton.setText("Novo cadastro");
        newButton.addActionListener(formListener);
        PanelCor.add(newButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 476, -1, -1));

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        deleteButton.setText("Deletar");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);
        PanelCor.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 476, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ManutençãoG.png"))); // NOI18N
        PanelCor.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Consulta de Manutenções");
        PanelCor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, -1, 40));

        lblPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPesquisar.setText("Pesquisar por:");
        PanelCor.add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, -1));

        cmbPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Nome do cliente", "Nome do funcionario"}));
        cmbPesquisar.addActionListener(formListener);
        PanelCor.add(cmbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 69, 128, -1));

        txtPesquisar.addKeyListener(formListener);
        PanelCor.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 69, 300, -1));

        refreshButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh-16.png"))); // NOI18N
        refreshButton1.setText("Atualizar");
        refreshButton1.addActionListener(formListener);
        PanelCor.add(refreshButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 476, -1, -1));

        btnGerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salario.png"))); // NOI18N
        btnGerar.setText("Gerar orçamento");
        btnGerar.setEnabled(false);
        btnGerar.addActionListener(formListener);
        PanelCor.add(btnGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 476, -1, -1));

        ConsultaManutencao.add(PanelCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ConsultaManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ConsultaManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.KeyListener, java.awt.event.MouseListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == btnFechar) {
                Consulta_Manutencao.this.btnFecharActionPerformed(evt);
            }
            else if (evt.getSource() == btnSalvar) {
                Consulta_Manutencao.this.btnSalvarActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                Consulta_Manutencao.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == txtInicio) {
                Consulta_Manutencao.this.txtInicioActionPerformed(evt);
            }
            else if (evt.getSource() == txtTotal) {
                Consulta_Manutencao.this.txtTotalActionPerformed(evt);
            }
            else if (evt.getSource() == txtDesconto) {
                Consulta_Manutencao.this.txtDescontoActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                Consulta_Manutencao.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                Consulta_Manutencao.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                Consulta_Manutencao.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == cmbPesquisar) {
                Consulta_Manutencao.this.cmbPesquisarActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton1) {
                Consulta_Manutencao.this.refreshButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == btnGerar) {
                Consulta_Manutencao.this.btnGerarActionPerformed(evt);
            }
        }

        public void keyPressed(java.awt.event.KeyEvent evt) {
        }

        public void keyReleased(java.awt.event.KeyEvent evt) {
            if (evt.getSource() == txtQtde) {
                Consulta_Manutencao.this.txtQtdeKeyReleased(evt);
            }
            else if (evt.getSource() == txtPreco) {
                Consulta_Manutencao.this.txtPrecoKeyReleased(evt);
            }
            else if (evt.getSource() == txtDesconto) {
                Consulta_Manutencao.this.txtDescontoKeyReleased(evt);
            }
            else if (evt.getSource() == nomeFuncionarioField) {
                Consulta_Manutencao.this.nomeFuncionarioFieldKeyReleased(evt);
            }
            else if (evt.getSource() == nomeClienteField) {
                Consulta_Manutencao.this.nomeClienteFieldKeyReleased(evt);
            }
            else if (evt.getSource() == codCliField) {
                Consulta_Manutencao.this.codCliFieldKeyReleased(evt);
            }
            else if (evt.getSource() == codFunField) {
                Consulta_Manutencao.this.codFunFieldKeyReleased(evt);
            }
            else if (evt.getSource() == txtPesquisar) {
                Consulta_Manutencao.this.txtPesquisarKeyReleased(evt);
            }
        }

        public void keyTyped(java.awt.event.KeyEvent evt) {
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == masterTable) {
                Consulta_Manutencao.this.masterTableMouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        ControleDeInstalacao LG = new ControleDeInstalacao();
        LG.setVisible(true);
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        salvar();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cmbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPesquisarActionPerformed

    //metodos usados no pesquisar!!!!!!!!!!!!!!
    public void mostraItens() {
        int seleciona = masterTable.getSelectedRow();
        codManutencaoField.setText(masterTable.getModel().getValueAt(seleciona, 0).toString());
        codCliField.setText(masterTable.getModel().getValueAt(seleciona, 1).toString());
        nomeClienteField.setText(masterTable.getModel().getValueAt(seleciona, 2).toString());
        codFunField.setText(masterTable.getModel().getValueAt(seleciona, 3).toString());
        nomeFuncionarioField.setText(masterTable.getModel().getValueAt(seleciona, 4).toString());
        ultimaManutencaoField.setText(masterTable.getModel().getValueAt(seleciona, 5).toString());
        proximaManutencaoField.setText(masterTable.getModel().getValueAt(seleciona, 6).toString());
        tipoManutencaoField.setText(masterTable.getModel().getValueAt(seleciona, 7).toString());
        descricaoDoProdutoField.setText(masterTable.getModel().getValueAt(seleciona, 8).toString());
        descricaoDoProblemaField.setText(masterTable.getModel().getValueAt(seleciona, 9).toString());
    }

    public void listarCadastros() {
        String sql = "Select * from manutencao order by Cod_Manutencao Asc ";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            masterTable.setModel(DbUtils.resultSetToTableModel(rs));
            txtPesquisar.setText("");
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);

        }
    }

    public void editarCadastros() {
        String sql = "Update manutencao set Cod_Cli =?, Nome_Cliente =? , Cod_Fun =? , Nome_Funcionario =?, Ultima_Manutencao =?, Proxima_Manutencao =?, Tipo_Manutencao =?, Descricao_Do_Produto =?, Descricao_Do_Problema =?  where Cod_Manutencao like ?";

        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, codCliField.getText());
            pst.setString(2, nomeClienteField.getText());
            pst.setString(3, codFunField.getText());
            pst.setString(4, nomeFuncionarioField.getText());
            pst.setString(5, ultimaManutencaoField.getText());
            pst.setString(6, proximaManutencaoField.getText());
            pst.setString(7, tipoManutencaoField.getText());
            pst.setString(8, descricaoDoProdutoField.getText());
            pst.setString(9, descricaoDoProblemaField.getText());
            pst.setString(10, codManutencaoField.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso.");
            listarCadastros();

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);

        }

    }

    public void PesquisarCadastros() {
        if (cmbPesquisar.getSelectedIndex() == 0) {
            String sql = "Select Cod_Manutencao, Cod_Cli , Nome_Cliente , Cod_Fun , Nome_Funcionario, Ultima_Manutencao, Proxima_Manutencao, Tipo_Manutencao, Descricao_Do_Produto, Descricao_Do_Problema from manutencao where Nome_Cliente like ?";

            try (Connection con = conexao.getConnection()) {
                PreparedStatement pst = con.prepareStatement(sql);

                pst = con.prepareStatement(sql);
                pst.setString(1, txtPesquisar.getText() + "%");
                rs = pst.executeQuery();
                masterTable.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException error) {
                JOptionPane.showMessageDialog(null, error);
            }
        }
        if (cmbPesquisar.getSelectedIndex() == 1) {
            String sql = "Select Cod_Manutencao, Cod_Cli , Nome_Cliente , Cod_Fun , Nome_Funcionario, Ultima_Manutencao, Proxima_Manutencao, Tipo_Manutencao, Descricao_Do_Produto, Descricao_Do_Problema from manutencao where Nome_Funcionario like ?";

            try (Connection con = conexao.getConnection()) {
                PreparedStatement pst = con.prepareStatement(sql);

                pst = con.prepareStatement(sql);
                pst.setString(1, txtPesquisar.getText() + "%");
                rs = pst.executeQuery();
                masterTable.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException error) {
                JOptionPane.showMessageDialog(null, error);
            }
        }
    }

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased

        PesquisarCadastros();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        mostraItens();
        btnGerar.setEnabled(true);
        mostraItemOrcamento();
    }//GEN-LAST:event_masterTableMouseClicked

    private void mostraItemOrcamento() {
        int seleciona = masterTable.getSelectedRow();
        codManutencaoField.setText(masterTable.getModel().getValueAt(seleciona, 0).toString());
        codCliField.setText(masterTable.getModel().getValueAt(seleciona, 8).toString());
        nomeClienteField.setText(masterTable.getModel().getValueAt(seleciona, 7).toString());
        codFunField.setText(masterTable.getModel().getValueAt(seleciona, 9).toString());
        nomeFuncionarioField.setText(masterTable.getModel().getValueAt(seleciona, 6).toString());
        ultimaManutencaoField.setText(masterTable.getModel().getValueAt(seleciona, 2).toString());
        proximaManutencaoField.setText(masterTable.getModel().getValueAt(seleciona, 4).toString());
        tipoManutencaoField.setText(masterTable.getModel().getValueAt(seleciona, 1).toString());
        descricaoDoProdutoField.setText(masterTable.getModel().getValueAt(seleciona, 3).toString());
        descricaoDoProblemaField.setText(masterTable.getModel().getValueAt(seleciona, 5).toString());
        
        txtVendedor.setText(masterTable.getModel().getValueAt(seleciona, 6).toString());
        txtDescricao.setText(masterTable.getModel().getValueAt(seleciona, 5).toString());
        
    }

    public void pegaNomeCli() {
        String sql = "select Nome from cad_cliente where Cod_Cli = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, codCliField.getText());
            rs = pst.executeQuery();
            rs.first();
            nomeClienteField.setText(rs.getString("Nome"));
        } catch (SQLException error) {

        }
    }

    public void pegaNomeFun() {
        String sql = "select Nome from cad_funcionario where Cod_Fun = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, codFunField.getText());
            rs = pst.executeQuery();
            rs.first();
            nomeFuncionarioField.setText(rs.getString("Nome"));
        } catch (SQLException error) {

        }
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String message = " Deseja realmente deletar esta manutenção? ";
        String title = "Mensagem de confirmação:";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            int[] selected = masterTable.getSelectedRows();
            List<dtcc.Manutencao> toRemove = new ArrayList<dtcc.Manutencao>(selected.length);
            for (int idx = 0; idx < selected.length; idx++) {
                dtcc.Manutencao m = list.get(masterTable.convertRowIndexToModel(selected[idx]));
                toRemove.add(m);
                entityManager.remove(m);
                salvar();
            }
            list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed
    }
    private void codCliFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codCliFieldKeyReleased
        pegaNomeCli();
    }//GEN-LAST:event_codCliFieldKeyReleased

    private void codFunFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codFunFieldKeyReleased
        pegaNomeFun();        // TODO add your handling code here:
    }//GEN-LAST:event_codFunFieldKeyReleased

    private void nomeClienteFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeClienteFieldKeyReleased
        pegaCodCli();        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteFieldKeyReleased

    private void nomeFuncionarioFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeFuncionarioFieldKeyReleased
        pegaCodFun();        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFuncionarioFieldKeyReleased

    private void refreshButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton1ActionPerformed
        atualizar();
    }//GEN-LAST:event_refreshButton1ActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        ConsultaManutencao.setVisible(true);
        GerarOrcamento.setVisible(true);
    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        ConsultaManutencao.setVisible(true);
        GerarOrcamento.setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if ((txtCliente.getText().isEmpty()) || (txtVendedor.getText().isEmpty()) || (txtAno.getText().isEmpty()) || (txtInicio.getText().equals("  /  /    ")) || (txtFim.getText().equals("  /  /    "))) {
            JOptionPane.showMessageDialog(null, "Alguns campos não podem retornar vazios");

        } else {
            pegaInformacoesDosCampos();
            od.inserirOrcamentos(ob);
            JOptionPane.showMessageDialog(null, "Orçamento cadastrado com sucesso! ", "Aviso", 1);
            apagarCampos();
        }                 // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limparCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicioActionPerformed

    private void txtQtdeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdeKeyReleased
        calculaValor();         // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdeKeyReleased

    private void txtPrecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoKeyReleased
        calculaValor();         // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoKeyReleased

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed

    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescontoActionPerformed

    private void txtDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyReleased
        calculaValor();        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescontoKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane ConsultaManutencao;
    private javax.swing.JInternalFrame GerarOrcamento;
    private javax.swing.JPanel PanelCor;
    private javax.swing.JComboBox Status;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbPesquisar;
    private javax.swing.JTextField codCliField;
    private javax.swing.JLabel codCliLabel;
    private javax.swing.JTextField codFunField;
    private javax.swing.JLabel codFunLabel;
    private javax.swing.JTextField codManutencaoField;
    private javax.swing.JLabel codManutencaoLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descricaoDoProblemaField;
    private javax.swing.JLabel descricaoDoProblemaLabel;
    private javax.swing.JTextField descricaoDoProdutoField;
    private javax.swing.JLabel descricaoDoProdutoLabel;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPesquisar;
    private java.util.List<dtcc.Manutencao> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField nomeClienteField;
    private javax.swing.JLabel nomeClienteLabel;
    private javax.swing.JTextField nomeFuncionarioField;
    private javax.swing.JLabel nomeFuncionarioLabel;
    private javax.swing.JTextField proximaManutencaoField;
    private javax.swing.JLabel proximaManutencaoLabel;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField tipoManutencaoField;
    private javax.swing.JLabel tipoManutencaoLabel;
    private javax.swing.JFormattedTextField txtAno;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodManutencao;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JFormattedTextField txtFim;
    private javax.swing.JFormattedTextField txtInicio;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JFormattedTextField txtPreco;
    private javax.swing.JFormattedTextField txtQtde;
    private javax.swing.JFormattedTextField txtTotal;
    private javax.swing.JTextField txtVendedor;
    private javax.swing.JTextField ultimaManutencaoField;
    private javax.swing.JLabel ultimaManutencaoLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public void run() {
        JFrame frame = new JFrame("Consulta de Manutenções");
        frame.setContentPane(new Consulta_Manutencao());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);

    }

    ;
    

    private void pegaCodCli() {
        String sql = "select Cod_Cli from cad_cliente where Nome = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, nomeClienteField.getText());
            rs = pst.executeQuery();
            rs.first();
            codCliField.setText(rs.getString("Cod_Cli"));
        } catch (SQLException error) {

        }
    }

    private void pegaCodFun() {
        String sql = "select Cod_Fun from cad_funcionario where Nome = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, nomeFuncionarioField.getText());
            rs = pst.executeQuery();
            rs.first();
            codFunField.setText(rs.getString("Cod_Fun"));
        } catch (SQLException error) {

        }
    }

    private void salvar() {
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
            editarCadastros();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<dtcc.Manutencao> merged = new ArrayList<dtcc.Manutencao>(list.size());
            for (dtcc.Manutencao m : list) {
                merged.add(entityManager.merge(m));
                atualizar();
            }
        }
    }

    private void atualizar() {
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
            btnGerar.setEnabled(false);
        }
        list.clear();
        list.addAll(data);
        listarCadastros();
    }

    private void calculaValor() {
        Double preco = Double.parseDouble(txtPreco.getText());
        Double desconto = Double.parseDouble(txtDesconto.getText());
        Double qtde = Double.parseDouble(txtQtde.getText());
        Double resultado = preco * qtde - desconto;
        String result = Double.toString(resultado);
        txtTotal.setText(result);
    }

    private void apagarCampos() {
        Status.setSelectedIndex(0);
        txtCliente.setText("");
        txtVendedor.setText("");
        txtAno.setText("");
        txtInicio.setText("");
        txtFim.setText("");
        txtDescricao.setText("");
        txtDesconto.setText("");
        txtPreco.setText("");
        txtTotal.setText("");
        txtQtde.setText("");

    }

    private void limparCampos() {
        String message = " Deseja realmente criar um novo orçamento? ";
        String title = "Novo Orçamento";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            apagarCampos();

        }
    }

    private void pegaInformacoesDosCampos() {
        ob = new OrcamentosBean();

        ob.setStatus(Status.getSelectedIndex());
        ob.setTxtCliente(txtCliente.getText());
        ob.setTxtVendedor(txtVendedor.getText());
        ob.setTxtAno(txtAno.getText());
        ob.setTxtInicio(txtInicio.getText());
        ob.setTxtFim(txtFim.getText());
        ob.setTxtDescricao(txtDescricao.getText());
        ob.setTxtDesconto(txtDesconto.getText());
        ob.setTxtPreco(txtPreco.getText());
        ob.setTxtTotal(txtTotal.getText());
        ob.setTxtQtde(txtQtde.getText());
    }
}
