/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtcc;

import java.awt.Toolkit;
import BancoDeDados.ControleDeInstalacaoBean;
import BancoDeDados.ControleDeInstalacaoDao;
import BancoDeDados.conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patricia
 */
public class ControleDeInstalacao extends javax.swing.JFrame {

    ResultSet rs;
    private DefaultTableModel DefaultTableModel;
    ControleDeInstalacaoDao cid = new ControleDeInstalacaoDao();
    ControleDeInstalacaoBean cib;

    public void pegaInformacoesDosCampos() {
        cib = new ControleDeInstalacaoBean();

        cib.setTxtCodCli(txtCodCli.getText());
        cib.setTxtNomeCli(txtNomeCli.getText());
        cib.setTxtCodFun(txtCodFun.getText());
        cib.setTxtNomeFun(txtNomeFun.getText());
        cib.setTxtPrimeiraManutencao(txtPrimeiraManutencao.getText());
        cib.setTxtDescricaoProduto(txtDescricaoProduto.getText());
        cib.setTxtDataInstalacao(txtDataInstalacao.getText());
        cib.setTxtHorario(txtHorario.getText());

    }

    /**
     * Creates new form tela_Orcamentos
     */
    public ControleDeInstalacao() {
        initComponents();
        txtDescricaoProduto.setLineWrap(true);
        setIcon();
    }

    public void limparCampos() {

        String message = " Deseja realmente criar uma nova instalação? ";
        String title = "Criar nova instalação";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            apagarCampos();

        }
    }

    public void apagarCampos() {
        txtCodigo.setText("");
        txtCodCli.setText("");
        txtNomeCli.setText("");
        txtCodFun.setText("");
        txtNomeFun.setText("");
        txtPrimeiraManutencao.setText("");
        txtDataInstalacao.setText("");
        txtHorario.setText("");
        txtDescricaoProduto.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNomeFun = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtCodCli = new javax.swing.JTextField();
        txtNomeCli = new javax.swing.JTextField();
        txtCodFun = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnNovaManutencao1 = new javax.swing.JButton();
        btnSair1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtHorario = new javax.swing.JFormattedTextField();
        txtPrimeiraManutencao = new javax.swing.JFormattedTextField();
        txtDataInstalacao = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescricaoProduto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Instalação");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Instalação");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Código:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Código do Cliente:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Nome do Cliente:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Nome do Funcionario:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Código do Funcionario:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtNomeFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeFunKeyReleased(evt);
            }
        });
        jPanel2.add(txtNomeFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 250, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 255));
        txtCodigo.setEnabled(false);
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 250, -1));

        txtCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodCliActionPerformed(evt);
            }
        });
        txtCodCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodCliKeyReleased(evt);
            }
        });
        jPanel2.add(txtCodCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 250, -1));

        txtNomeCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeCliKeyReleased(evt);
            }
        });
        jPanel2.add(txtNomeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 250, -1));

        txtCodFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodFunKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodFunKeyReleased(evt);
            }
        });
        jPanel2.add(txtCodFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 250, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Primeira Manutenção:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Descrição do Produto:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        btnNovaManutencao1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaManutencao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Manutenção.png"))); // NOI18N
        btnNovaManutencao1.setText("Nova Instalação");
        btnNovaManutencao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaManutencao1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNovaManutencao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 160, -1));

        btnSair1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair peq.png"))); // NOI18N
        btnSair1.setText("Sair");
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 90, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Data da Instalação:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Horario:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        try {
            txtHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 120, -1));

        try {
            txtPrimeiraManutencao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtPrimeiraManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 120, -1));

        try {
            txtDataInstalacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtDataInstalacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 120, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Instalação G.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar peq.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 90, -1));

        txtDescricaoProduto.setColumns(20);
        txtDescricaoProduto.setRows(5);
        jScrollPane3.setViewportView(txtDescricaoProduto);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 300, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(841, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaManutencao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaManutencao1ActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnNovaManutencao1ActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        ControleDeInstalacao LG = new ControleDeInstalacao();
        LG.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnSair1ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if ((txtNomeCli.getText().isEmpty()) || (txtCodCli.getText().isEmpty()) || (txtCodFun.getText().isEmpty()) || (txtNomeFun.getText().isEmpty()) || (txtDescricaoProduto.getText().isEmpty()) || (txtHorario.getText().equals("  :  ")) || (txtPrimeiraManutencao.getText().equals("  /  /    ")) || (txtDataInstalacao.getText().equals("  /  /    "))) {
            JOptionPane.showMessageDialog(null, "Alguns campos não podem retornar vazios");
        } else {
            pegaInformacoesDosCampos();
            cid.inserirInstalacao(cib);
            JOptionPane.showMessageDialog(null, "Instalação cadastrada com sucesso! ", "Aviso", 1);
            apagarCampos();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCodCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodCliKeyReleased
        pegaNomeCli();
    }//GEN-LAST:event_txtCodCliKeyReleased

    private void txtCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodCliActionPerformed

    }//GEN-LAST:event_txtCodCliActionPerformed

    private void txtNomeCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCliKeyReleased
        pegaCodCli();
    }//GEN-LAST:event_txtNomeCliKeyReleased

    private void txtCodFunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodFunKeyReleased
        pegaNomeFun();
    }//GEN-LAST:event_txtCodFunKeyReleased

    private void txtNomeFunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFunKeyReleased
        pegaCodFun();
    }//GEN-LAST:event_txtNomeFunKeyReleased

    private void txtCodFunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodFunKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodFunKeyPressed

    public void run() {
        new ControleDeInstalacao().setVisible(true);

    }
    ;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovaManutencao1;
    private javax.swing.JButton btnSair1;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtCodCli;
    private javax.swing.JTextField txtCodFun;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtDataInstalacao;
    private javax.swing.JTextArea txtDescricaoProduto;
    private javax.swing.JFormattedTextField txtHorario;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtNomeFun;
    private javax.swing.JFormattedTextField txtPrimeiraManutencao;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconframe.png"))); //To change body of generated methods, choose Tools | Templates.
    }

    private void pegaNomeCli() {
        String sql = "select Nome from cad_cliente where Cod_Cli = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtCodCli.getText());
            rs = pst.executeQuery();
            rs.first();
            txtNomeCli.setText(rs.getString("Nome"));
        } catch (SQLException error) {

        }

    }

    private void pegaCodCli() {
        String sql = "select Cod_Cli from cad_cliente where Nome = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtNomeCli.getText());
            rs = pst.executeQuery();
            rs.first();
            txtCodCli.setText(rs.getString("Cod_Cli"));
        } catch (SQLException error) {

        }
    }

    private void pegaNomeFun() {
        String sql = "select Nome from cad_funcionario where Cod_Fun = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtCodFun.getText());
            rs = pst.executeQuery();
            rs.first();
            txtNomeFun.setText(rs.getString("Nome"));
        } catch (SQLException error) {

        }
    }

    private void pegaCodFun() {
        String sql = "select Cod_Fun from cad_funcionario where Nome = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtNomeFun.getText());
            rs = pst.executeQuery();
            rs.first();
            txtCodFun.setText(rs.getString("Cod_Fun"));
        } catch (SQLException error) {

        }
    }
}
