/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtcc;

import java.awt.Toolkit;
import BancoDeDados.ControleDeManutencaoBean;
import BancoDeDados.ControleDeManutencaoDao;
import BancoDeDados.conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patricia
 */
public class ControleDeManutencao extends javax.swing.JFrame {

    ResultSet rs;
    private DefaultTableModel DefaultTableModel;
    ControleDeManutencaoDao cmd = new ControleDeManutencaoDao();
    ControleDeManutencaoBean cmb;

    public void pegaInformacoesDosCampos() {
        cmb = new ControleDeManutencaoBean();

        cmb.setTipo(cmbTipo.getSelectedIndex());
        cmb.setTxtUltima(txtUltima.getText());
        cmb.setTxtDescricaoProduto(txtDescricaoProduto.getText());
        cmb.setTxtProxima(txtProxima.getText());
        cmb.setTxtDescricaoProblema(txtDescricaoProblema.getText());
        cmb.setTxtNomeFun(txtNomeFun.getText());
        cmb.setTxtNomeCli(txtNomeCli.getText());
        cmb.setTxtCodCli(txtCodCli.getText());
        cmb.setTxtCodFun(txtCodFun.getText());
       

    }

    public ControleDeManutencao() {
        initComponents();
        txtDescricaoProduto.setLineWrap(true);
        txtDescricaoProblema.setLineWrap(true);
        setIcon();
    }

    public void limparCampos() {

        String message = " Deseja realmente criar uma nova manutenção? ";
        String title = "Criar nova manutenção";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            apagarCampos();

        }
    }

    public void apagarCampos() {
        txtCodigo.setText("");
        txtCodCli.setText("");
        txtNomeCli.setText("");
        txtCodFun.setText("");
        txtUltima.setText("");
        txtProxima.setText("");
        txtNomeFun.setText("");
        txtDescricaoProduto.setText("");
        txtDescricaoProblema.setText("");
        cmbTipo.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCodCli = new javax.swing.JTextField();
        txtNomeCli = new javax.swing.JTextField();
        txtCodFun = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNovaManutencao = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox();
        txtNomeFun = new javax.swing.JTextField();
        txtProxima = new javax.swing.JFormattedTextField();
        txtUltima = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        btnSalvar2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescricaoProblema = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescricaoProduto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Manutenção");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Manutenção");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Código:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Código do Cliente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nome do Cliente:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nome do Funcionario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Código do Funcionario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 255));
        txtCodigo.setEnabled(false);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 250, -1));

        txtCodCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodCliKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 250, -1));

        txtNomeCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeCliKeyReleased(evt);
            }
        });
        jPanel1.add(txtNomeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 250, -1));

        txtCodFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodFunKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 250, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Última:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Próxima:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Descrição do Produto:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Tipo de manutenção:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Descrição do Problema:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, 10));

        btnNovaManutencao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNovaManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Manutenção.png"))); // NOI18N
        btnNovaManutencao.setText("Nova Manutenção");
        btnNovaManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaManutencaoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovaManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair peq.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 80, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0- Preventiva", "1- Corretiva" }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 130, -1));

        txtNomeFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeFunKeyReleased(evt);
            }
        });
        jPanel1.add(txtNomeFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 250, -1));

        try {
            txtProxima.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtProxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 110, -1));

        try {
            txtUltima.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtUltima, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 110, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ManutençãoG.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnSalvar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar peq.png"))); // NOI18N
        btnSalvar2.setText("Salvar");
        btnSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 90, -1));

        txtDescricaoProblema.setColumns(20);
        txtDescricaoProblema.setRows(5);
        jScrollPane3.setViewportView(txtDescricaoProblema);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 330, 60));

        txtDescricaoProduto.setColumns(20);
        txtDescricaoProduto.setRows(5);
        jScrollPane4.setViewportView(txtDescricaoProduto);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 330, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(841, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaManutencaoActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnNovaManutencaoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        ControleDeManutencao LG = new ControleDeManutencao();
        LG.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar2ActionPerformed
        if ((txtCodCli.getText().isEmpty()) || (txtCodFun.getText().isEmpty()) || (txtDescricaoProblema.getText().isEmpty()) || (txtDescricaoProduto.getText().isEmpty()) || (txtNomeCli.getText().isEmpty()) || (txtNomeFun.getText().isEmpty()) || (txtUltima.getText().equals("  /  /    ")) || (txtProxima.getText().equals("  /  /    "))) {
            JOptionPane.showMessageDialog(null, "Alguns campos não podem retornar vazios");
        } else {
            pegaInformacoesDosCampos();
            cmd.inserirManutencao(cmb);
            JOptionPane.showMessageDialog(null, "Manutenção cadastrada com sucesso! ", "Aviso", 1);
            apagarCampos();
        }

    }//GEN-LAST:event_btnSalvar2ActionPerformed

    private void txtCodCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodCliKeyReleased
        pegaNomeCli();
    }//GEN-LAST:event_txtCodCliKeyReleased

    private void txtNomeCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCliKeyReleased
        pegaCodCli();
    }//GEN-LAST:event_txtNomeCliKeyReleased

    private void txtCodFunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodFunKeyReleased
        pegaNomeFun();         // TODO add your handling code here:
    }//GEN-LAST:event_txtCodFunKeyReleased

    private void txtNomeFunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFunKeyReleased
        pegaCodFun();
    }//GEN-LAST:event_txtNomeFunKeyReleased

    public void run() {
        new ControleDeManutencao().setVisible(true);

    }
    ;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovaManutencao;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar2;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtCodCli;
    private javax.swing.JTextField txtCodFun;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescricaoProblema;
    private javax.swing.JTextArea txtDescricaoProduto;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtNomeFun;
    private javax.swing.JFormattedTextField txtProxima;
    private javax.swing.JFormattedTextField txtUltima;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconframe.png"))); //To change body of generated methods, choose Tools | Templates.
    }

    private void pegaNomeCli() {
        String sql = "select Nome from cad_cliente where Cod_Cli = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtCodCli.getText());
            rs = pst.executeQuery();
            rs.first();
            txtNomeCli.setText(rs.getString("Nome"));
        } catch (SQLException error) {

        }
    }

    private void pegaCodCli() {
        String sql = "select Cod_Cli from cad_cliente where Nome = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtNomeCli.getText());
            rs = pst.executeQuery();
            rs.first();
            txtCodCli.setText(rs.getString("Cod_Cli"));
        } catch (SQLException error) {

        }
    }

    private void pegaNomeFun() {
        String sql = "select Nome from cad_funcionario where Cod_Fun = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtCodFun.getText());
            rs = pst.executeQuery();
            rs.first();
            txtNomeFun.setText(rs.getString("Nome"));
        } catch (SQLException error) {

        }
    }

    private void pegaCodFun() {
        String sql = "select Cod_Fun from cad_funcionario where Nome = ?";
        try (Connection con = conexao.getConnection()) {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtNomeFun.getText());
            rs = pst.executeQuery();
            rs.first();
            txtCodFun.setText(rs.getString("Cod_Fun"));
        } catch (SQLException error) {

        }
    }
}
