package dtcc;

import dtcc.*;
import BD.AutentiacacaoDoEmail;
import BD.TratamentoDeEmail;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Windows
 */
public class Email extends javax.swing.JFrame {

    /**
     * Creates new form InternalFrame
     */
    public Email() {
        initComponents();
        setIcon();
        txtMensagem.setLineWrap(true);
        DPane.setVisible(false);
        IFrame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DPane = new javax.swing.JDesktopPane();
        IFrame = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAssunto = new javax.swing.JTextField();
        txtDestinatario = new javax.swing.JTextField();
        txtNovo = new javax.swing.JButton();
        txtDeslogar = new javax.swing.JButton();
        txtEnviar = new javax.swing.JButton();
        txtSair = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLogin2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JPSSenha2 = new javax.swing.JPasswordField();
        btnLogar2 = new javax.swing.JButton();
        btnLimpar2 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Email");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DPane.setBackground(new java.awt.Color(255, 255, 255));
        DPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IFrame.setTitle("Enviar Email");
        IFrame.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/email grande.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enviar E-Mail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Assunto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("E-Mail Destinatário:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mensagem:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, -1));
        jPanel1.add(txtAssunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 116, 400, -1));
        jPanel1.add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 154, 400, -1));

        txtNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        txtNovo.setText("Novo");
        txtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, -1));

        txtDeslogar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDeslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar peq.png"))); // NOI18N
        txtDeslogar.setText("Deslogar");
        txtDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeslogarActionPerformed(evt);
            }
        });
        jPanel1.add(txtDeslogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        txtEnviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Email.png"))); // NOI18N
        txtEnviar.setText("Enviar E-Mail!");
        txtEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(txtEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 150, -1));

        txtSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair_1.png"))); // NOI18N
        txtSair.setText("Sair");
        txtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSairActionPerformed(evt);
            }
        });
        jPanel1.add(txtSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 80, -1));

        lblNome.setText("Bem Vindo: ");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 200, -1));

        txtMensagem.setColumns(20);
        txtMensagem.setRows(5);
        jScrollPane3.setViewportView(txtMensagem);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 390, 170));

        javax.swing.GroupLayout IFrameLayout = new javax.swing.GroupLayout(IFrame.getContentPane());
        IFrame.getContentPane().setLayout(IFrameLayout);
        IFrameLayout.setHorizontalGroup(
            IFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );
        IFrameLayout.setVerticalGroup(
            IFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        DPane.add(IFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));
        DPane.setLayer(IFrame, javax.swing.JLayeredPane.POPUP_LAYER);

        getContentPane().add(DPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/email grande.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Digite seu E-mail:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, 30));

        txtLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogin2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 330, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Digite sua Senha:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, 30));
        getContentPane().add(JPSSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 330, 30));

        btnLogar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Check.png"))); // NOI18N
        btnLogar2.setText("Logar");
        btnLogar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 150, -1));

        btnLimpar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remove.png"))); // NOI18N
        btnLimpar2.setText("Limpar");
        btnLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 150, -1));

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair peq.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Bem Vindo!");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/teste.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Email LG = new Email();
        LG.setVisible(false);
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar2ActionPerformed
        txtLogin2.setText("");
        JPSSenha2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar2ActionPerformed

    private void btnLogar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogar2ActionPerformed
        if (txtLogin2.getText().isEmpty() || JPSSenha2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Os campos não podem estar vazios", "Autenticação de e-mail", JOptionPane.WARNING_MESSAGE);

        } else {

            String email = "";
            String emaill = txtLogin2.getText();
            email = emaill;
            String nome = "";
            String url = "";
            int valida = emaill.lastIndexOf("@");

            if (valida >= 0) {
                nome = email.substring(0, valida);
                url = email.substring(valida + 1);

                AutentiacacaoDoEmail autentica = new AutentiacacaoDoEmail();
                autentica.enviarEmail(txtLogin2.getText(), JPSSenha2.getText());

                IFrame.setVisible(true);

                lblNome.setText("Bem vindo " + nome);
                DPane.setVisible(true);

            } else {

                JOptionPane.showMessageDialog(null, "Endereço de e-mail digitado é invalido", "Autenticação de e-mail", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnLogar2ActionPerformed

    private void txtLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogin2ActionPerformed

    private void txtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSairActionPerformed
        Email LG = new Email();
        LG.setVisible(false);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSairActionPerformed

    private void txtEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnviarActionPerformed
        String emaill = txtDestinatario.getText();
        int valida = emaill.lastIndexOf("@");
        String nome = "";
        String url = "";
        if (valida >= 0) {
            nome = emaill.substring(0, valida);
            url = emaill.substring(valida + 1);
            String seuEmail1 = txtLogin2.getText();
            String suaSenha1 = JPSSenha2.getText();
            String assunto1 = txtAssunto.getText();
            String emailDestinatario1 = txtDestinatario.getText();
            String conteudo1 = txtMensagem.getText();

            TratamentoDeEmail enviando = new TratamentoDeEmail();
            enviando.enviarEmail(seuEmail1, suaSenha1, assunto1, conteudo1, emailDestinatario1);

            JOptionPane.showMessageDialog(null, "O email foi enviado para: " + emailDestinatario1, " e-mail enviado com sucesso", JOptionPane.PLAIN_MESSAGE);
            txtAssunto.setText("");
            txtMensagem.setText("");
            txtDestinatario.setText("");
        } else {

            JOptionPane.showMessageDialog(null, "Endereço de e-mail: " + emaill + " digitado é invalido", "Autenticação de e-mail", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtEnviarActionPerformed

    private void txtDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeslogarActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do e-mail ?", "Mensagem de Confirmação", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {

            txtLogin2.setText("");
            JPSSenha2.setText("");
            IFrame.setVisible(false);
            DPane.setVisible(false);

        } else {
            return;
        }
    }//GEN-LAST:event_txtDeslogarActionPerformed

    private void txtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovoActionPerformed
        txtAssunto.setText("");
        txtDestinatario.setText("");
        txtMensagem.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_txtNovoActionPerformed

    public void run() {
        new Email().setVisible(true);

    }
    ;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DPane;
    private javax.swing.JInternalFrame IFrame;
    private javax.swing.JPasswordField JPSSenha2;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JButton btnLogar2;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JButton txtDeslogar;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JButton txtEnviar;
    private javax.swing.JTextField txtLogin2;
    private javax.swing.JTextArea txtMensagem;
    private javax.swing.JButton txtNovo;
    private javax.swing.JButton txtSair;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconframe.png"))); //To change body of generated methods, choose Tools | Templates.
    }
}
