/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtcc;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * )
 *
 * @author Jéssica
 */
public class FrontEnd extends javax.swing.JFrame {

    data mostra_data;

    Email email = new Email();

    public FrontEnd() {
        initComponents();
        mostra_data = new data();
        mostra_data.le_data();

        mostra_data.le_hora();
        label_data.setText(mostra_data.dia_semana + ", " + mostra_data.dia + " de " + mostra_data.mes + " de " + mostra_data.ano);
        timer2.start();
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label_hora = new javax.swing.JLabel();
        label_data = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Cadastros = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Dados_Cadastrais = new javax.swing.JMenuItem();
        Controle = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        ConsultaCadastro = new javax.swing.JMenu();
        ConsultaCliente = new javax.swing.JMenuItem();
        ConsultaFuncionarios = new javax.swing.JMenuItem();
        ConsultaFornecedores = new javax.swing.JMenuItem();
        ConsultaProdutos = new javax.swing.JMenuItem();
        ConsultaControle = new javax.swing.JMenu();
        ConsultaOrcamento = new javax.swing.JMenuItem();
        ConsultaInstalacao = new javax.swing.JMenuItem();
        ConsultaManutencao = new javax.swing.JMenuItem();
        Acessorios = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        Banking = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        Ajuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atende Ar Condicionado e Refrigeração");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 183, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/power.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -52;
        gridBagConstraints.ipady = -29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 82, 11, 84);
        jPanel2.add(jButton1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(85, 33, 11, 0);
        jPanel2.add(label_hora, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(85, 183, 11, 0);
        jPanel2.add(label_data, gridBagConstraints);

        Cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastros.png"))); // NOI18N
        Cadastros.setText("Cadastros");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cliente peq.png"))); // NOI18N
        jMenuItem3.setText("Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Cadastros.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Funcionario peq.png"))); // NOI18N
        jMenuItem4.setText("Funcionários");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Cadastros.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fornecedores peq.png"))); // NOI18N
        jMenuItem5.setText("Fornecedores");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Cadastros.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Produto.png"))); // NOI18N
        jMenuItem6.setText("Produtos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Cadastros.add(jMenuItem6);

        Dados_Cadastrais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        Dados_Cadastrais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Empresa.png"))); // NOI18N
        Dados_Cadastrais.setText("Dados Empresariais");
        Dados_Cadastrais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dados_CadastraisActionPerformed(evt);
            }
        });
        Cadastros.add(Dados_Cadastrais);

        Menu.add(Cadastros);

        Controle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Financeiro.png"))); // NOI18N
        Controle.setText("Controle ");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salario.png"))); // NOI18N
        jMenuItem10.setText("Orçamentos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        Controle.add(jMenuItem10);

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Instalaçao.png"))); // NOI18N
        jMenuItem20.setText("Instalação");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        Controle.add(jMenuItem20);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Manutenção.png"))); // NOI18N
        jMenuItem12.setText("Manutenção");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        Controle.add(jMenuItem12);

        Menu.add(Controle);

        Consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        Consultas.setText("Consultas");

        ConsultaCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastros.png"))); // NOI18N
        ConsultaCadastro.setText("Cadastro");

        ConsultaCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        ConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cliente peq.png"))); // NOI18N
        ConsultaCliente.setText("Clientes");
        ConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaClienteActionPerformed(evt);
            }
        });
        ConsultaCadastro.add(ConsultaCliente);

        ConsultaFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        ConsultaFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Funcionario peq.png"))); // NOI18N
        ConsultaFuncionarios.setText("Funcionarios");
        ConsultaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaFuncionariosActionPerformed(evt);
            }
        });
        ConsultaCadastro.add(ConsultaFuncionarios);

        ConsultaFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        ConsultaFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fornecedores peq.png"))); // NOI18N
        ConsultaFornecedores.setText("Fornecedores");
        ConsultaFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaFornecedoresActionPerformed(evt);
            }
        });
        ConsultaCadastro.add(ConsultaFornecedores);

        ConsultaProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        ConsultaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Produto.png"))); // NOI18N
        ConsultaProdutos.setText("Produtos");
        ConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaProdutosActionPerformed(evt);
            }
        });
        ConsultaCadastro.add(ConsultaProdutos);

        Consultas.add(ConsultaCadastro);

        ConsultaControle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Financeiro.png"))); // NOI18N
        ConsultaControle.setText("Controle");

        ConsultaOrcamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_MASK));
        ConsultaOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salario.png"))); // NOI18N
        ConsultaOrcamento.setText("Orçamento");
        ConsultaOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaOrcamentoActionPerformed(evt);
            }
        });
        ConsultaControle.add(ConsultaOrcamento);

        ConsultaInstalacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_MASK));
        ConsultaInstalacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Instalaçao.png"))); // NOI18N
        ConsultaInstalacao.setText("Instalação");
        ConsultaInstalacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaInstalacaoActionPerformed(evt);
            }
        });
        ConsultaControle.add(ConsultaInstalacao);

        ConsultaManutencao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_MASK));
        ConsultaManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Manutenção.png"))); // NOI18N
        ConsultaManutencao.setText("Manutenção");
        ConsultaManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaManutencaoActionPerformed(evt);
            }
        });
        ConsultaControle.add(ConsultaManutencao);

        Consultas.add(ConsultaControle);

        Menu.add(Consultas);

        Acessorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Acessorios.png"))); // NOI18N
        Acessorios.setText("Acessorios");

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Agenda peq.png"))); // NOI18N
        jMenuItem19.setText("Agenda");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        Acessorios.add(jMenuItem19);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Calculadora.png"))); // NOI18N
        jMenuItem7.setText("Calculadora");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Acessorios.add(jMenuItem7);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        jMenuItem16.setText("GPS");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        Acessorios.add(jMenuItem16);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Email.png"))); // NOI18N
        jMenuItem8.setText("Enviar E-mail");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Acessorios.add(jMenuItem8);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Email.png"))); // NOI18N
        jMenuItem13.setText("Outlook");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        Acessorios.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excel.png"))); // NOI18N
        jMenuItem14.setText("Excel");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        Acessorios.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Word.png"))); // NOI18N
        jMenuItem15.setText("Word");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        Acessorios.add(jMenuItem15);

        Menu.add(Acessorios);

        Banking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/banking.png"))); // NOI18N
        Banking.setText("Banking");

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/itau.20120516190509.jpg"))); // NOI18N
        jMenuItem17.setText("Itaú");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        Banking.add(jMenuItem17);

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sant.jpg"))); // NOI18N
        jMenuItem18.setText("Santander");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        Banking.add(jMenuItem18);

        Menu.add(Banking);

        Ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Ajuda.png"))); // NOI18N
        Ajuda.setText("Ajuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pdf.png"))); // NOI18N
        jMenuItem1.setText("Manual");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Ajuda.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Informação.png"))); // NOI18N
        jMenuItem2.setText("Contato");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Ajuda.add(jMenuItem2);

        Menu.add(Ajuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(868, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//System.exit(0);    }//GEN-LAST:event_jButton1ActionPerformed

        int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Mensagem de confirmação:", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {

            System.exit(0);
        }
    }
    private void timer2OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer2OnTime
        // TODO add your handling code here:

        mostra_data.le_hora();
        label_hora.setText(" " + mostra_data.hora);
    }//GEN-LAST:event_timer2OnTime

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Contato LG = new Contato();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        Desktop desk = java.awt.Desktop.getDesktop();
        try {
            desk.browse(new java.net.URI("http://www.santander.com.br//"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        Desktop desk = java.awt.Desktop.getDesktop();
        try {
            desk.browse(new java.net.URI("http://www.itau.com.br//"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        Gpsgui LG = new Gpsgui();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        //word
        try {

            Runtime.getRuntime().exec("cmd /c start winword.exe "); //aqui você adiciona os .exe que quiser abrir
        } catch (Exception erro) {
            System.err.println("Erro ao abrir aplicativo");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        //excel
        try {

            Runtime.getRuntime().exec("cmd /c start excel.exe "); //aqui você adiciona os .exe que quiser abrir
        } catch (Exception erro) {
            System.err.println("Erro ao abrir aplicativo");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        //email
        try {

            Runtime.getRuntime().exec("cmd /c start outlook.exe"); //aqui você adiciona os .exe que quiser abrir
        } catch (Exception erro) {
            System.err.println("Erro ao abrir aplicativo");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            //Calculadora
            Runtime.getRuntime().exec("C:\\Windows\\System32\\calc.exe"); //aqui você adiciona os .exe que quiser abrir
        } catch (Exception erro) {
            Calculadora Propriedades_Calculadora = new Calculadora();
            // Define o tamanho da tela    
            Propriedades_Calculadora.setSize(255, 330);
            // Fecha a janela    
            Propriedades_Calculadora.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            // Torna a janela visível    
            Propriedades_Calculadora.setVisible(true);
            // Desabilita o maximizar    
            Propriedades_Calculadora.setResizable(false);
            // Abre a janela no meio da tela    
            Propriedades_Calculadora.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        AgendaDeTarefas LG = new AgendaDeTarefas();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        tela_Orcamentos LG = new tela_Orcamentos();
        LG.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void Dados_CadastraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dados_CadastraisActionPerformed
        DadosCadastrais LG = new DadosCadastrais();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Dados_CadastraisActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        CadProduto LG = new CadProduto();
        LG.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CadFornecedor LG = new CadFornecedor();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CadFuncionario LG = new CadFuncionario();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CadCliente LG = new CadCliente();
        LG.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        ControleDeManutencao LG = new ControleDeManutencao();
        LG.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        ControleDeInstalacao LG = new ControleDeInstalacao();
        LG.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (email == null) {
            email = new Email();
            email.setVisible(true);
        } else {
            email.setVisible(true);
            email.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void ConsultaOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaOrcamentoActionPerformed
        JFrame frame = new JFrame("Consulta de Orçamentos");
        frame.setContentPane(new Consulta_Orcamento());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);
    }//GEN-LAST:event_ConsultaOrcamentoActionPerformed

    private void ConsultaManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaManutencaoActionPerformed
        JFrame frame = new JFrame("Consulta de Manutenções");
        frame.setContentPane(new Consulta_Manutencao());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaManutencaoActionPerformed

    private void ConsultaInstalacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaInstalacaoActionPerformed
        JFrame frame = new JFrame("Consulta de Instalações");
        frame.setContentPane(new Consulta_Instalacao());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaInstalacaoActionPerformed

    private void ConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaClienteActionPerformed
        JFrame frame = new JFrame("Consulta de Clientes");
        frame.setContentPane(new Consulta_Clientes());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);
    }//GEN-LAST:event_ConsultaClienteActionPerformed

    private void ConsultaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaFuncionariosActionPerformed
        JFrame frame = new JFrame("Consulta de Funcionarios");
        frame.setContentPane(new Consulta_Funcionario());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaFuncionariosActionPerformed

    private void ConsultaFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaFornecedoresActionPerformed
        JFrame frame = new JFrame("Consulta de Fornecedores");
        frame.setContentPane(new Consulta_Fornecedor());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);
    }//GEN-LAST:event_ConsultaFornecedoresActionPerformed

    private void ConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaProdutosActionPerformed
        JFrame frame = new JFrame("Consulta de Produtos");
        frame.setContentPane(new Consulta_Produtos());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setResizable(false); //desabilita maximizar
        frame.setLocationRelativeTo(null);  //centraliza Jframe
        frame.setVisible(true);
    }//GEN-LAST:event_ConsultaProdutosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            File file = new File("./Manual/manual.pdf");
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void run() {
        new FrontEnd().setVisible(true);

    }
    ;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acessorios;
    private javax.swing.JMenu Ajuda;
    private javax.swing.JMenu Banking;
    private javax.swing.JMenu Cadastros;
    private javax.swing.JMenu ConsultaCadastro;
    private javax.swing.JMenuItem ConsultaCliente;
    private javax.swing.JMenu ConsultaControle;
    private javax.swing.JMenuItem ConsultaFornecedores;
    private javax.swing.JMenuItem ConsultaFuncionarios;
    private javax.swing.JMenuItem ConsultaInstalacao;
    private javax.swing.JMenuItem ConsultaManutencao;
    private javax.swing.JMenuItem ConsultaOrcamento;
    private javax.swing.JMenuItem ConsultaProdutos;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenu Controle;
    private javax.swing.JMenuItem Dados_Cadastrais;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_hora;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconframe.png"))); //To change body of generated methods, choose Tools | Templates.
    }
}
