package dtcc;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import com.br.jhonatan2760.Forecast;
import javax.swing.JOptionPane;

/**
 *
 * @author Desenvolvimento
 */
public class Gpsgui extends javax.swing.JFrame {

    /**
     * Creates new form Gpsgui
     */
    public Gpsgui() {
        initComponents();
        setIcon();
    }

    public void limparCampos() {

        String message = " Deseja realmente criar uma nova rota? ";
        String title = "Criar nova rota";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            j_ende.setText("");
            j_ori.setText("");
            texto.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        j_ende = new javax.swing.JTextField();
        lbl_origem = new javax.swing.JLabel();
        lbl_ond = new javax.swing.JLabel();
        j_ori = new javax.swing.JTextField();
        gerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Rotas");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 20));

        j_ende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_endeActionPerformed(evt);
            }
        });
        getContentPane().add(j_ende, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, -1));

        lbl_origem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_origem.setText("Onde você esta:");
        getContentPane().add(lbl_origem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        lbl_ond.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ond.setText("Seu destino:");
        getContentPane().add(lbl_ond, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        j_ori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_oriActionPerformed(evt);
            }
        });
        getContentPane().add(j_ori, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, -1));

        gerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gerar Rota.png"))); // NOI18N
        gerar.setText("Gerar rota");
        gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarActionPerformed(evt);
            }
        });
        getContentPane().add(gerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        texto.setEditable(false);
        texto.setAutoscrolls(false);
        texto.setDoubleBuffered(true);
        jScrollPane1.setViewportView(texto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 520, 120));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Pesquisa de Rotas");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 13, -1, -1));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar grande.png"))); // NOI18N
        bg.setOpaque(true);
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 50, 40));

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        btnLimpar.setText("Nova rota");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair peq.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 337, 80, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tempo.png"))); // NOI18N
        jButton2.setText("Temperatura atual");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel2.setText("MAPS(R) Powered by GoogleMaps");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 170, -1));

        jLabel1.setText("Weather powered by ClimaTempo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 260, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        getAccessibleContext().setAccessibleName("Pesquisa de rotas");

        setSize(new java.awt.Dimension(602, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarActionPerformed
        Gps g = new Gps();
        texto.setText(g.calcular(j_ende.getText(), j_ori.getText()).replaceAll("</b>", "\n").replace("<b>", ""));

    }//GEN-LAST:event_gerarActionPerformed

    private void j_endeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_endeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_endeActionPerformed

    private void j_oriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_oriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_oriActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Gpsgui LG = new Gpsgui();
        LG.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Forecast load = new Forecast("saopaulo", "SP");
        String b = load.getTemperatura();
        JOptionPane.showMessageDialog(null, "Temperatura atual de São Paulo: " + Forecast.getTemperatura(), "Temperatura Atual", JOptionPane.INFORMATION_MESSAGE);
        System.out.println("Temperatura atual de São Paulo: " + Forecast.getTemperatura());
    }//GEN-LAST:event_jButton2ActionPerformed

    public void run() {
        new Gpsgui().setVisible(true);

    }
    ;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton gerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField j_ende;
    private javax.swing.JTextField j_ori;
    private javax.swing.JLabel lbl_ond;
    private javax.swing.JLabel lbl_origem;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconframe.png"))); //To change body of generated methods, choose Tools | Templates.
    }
}
